import { useState } from "react"
import { FileText, Download, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Textarea } from "@/components/ui/textarea"

interface Recommendation {
  tool: string
  confidence: number
  steps: string[]
  reasoning: string
}

interface ActionPlanExportProps {
  recommendation: Recommendation
  task: string
}

export default function ActionPlanExport({ recommendation, task }: ActionPlanExportProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [copied, setCopied] = useState(false)

  const generateActionPlan = () => {
    return `ACTION PLAN
==========

Task: ${task}

Recommended Tool: ${recommendation.tool}
Confidence: ${recommendation.confidence}%

STEPS:
${recommendation.steps.map((step, i) => `${i + 1}. ${step}`).join('\n')}

REASONING:
${recommendation.reasoning}

Generated by TaskRouter - ${new Date().toLocaleDateString()}`
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(generateActionPlan())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = () => {
    const blob = new Blob([generateActionPlan()], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `action-plan-${Date.now()}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="secondary" className="flex-1">
          <FileText className="h-4 w-4 mr-2" />
          Export Plan
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Export Action Plan
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <Textarea
            value={generateActionPlan()}
            readOnly
            className="min-h-[300px] font-mono text-sm"
          />
          <div className="flex gap-3">
            <Button 
              variant="outline" 
              className="flex-1"
              onClick={handleCopy}
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4 mr-2" />
                  Copied!
                </>
              ) : (
                "Copy to Clipboard"
              )}
            </Button>
            <Button 
              className="flex-1"
              onClick={handleDownload}
            >
              <Download className="h-4 w-4 mr-2" />
              Download .txt
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}