from pathlib import Path

path = Path('e2e/mobile-agent-generation.spec.cjs')
text = path.read_text(encoding='utf-8')
old = """  return (systemText, userText, stream) => {\n    if (systemText.includes('SKELETON: Mobile App')) return markers;\n    if (systemText.includes('fixing prototype quality gate failures')) return markers;\n    if (systemText.includes('Pass 2 critic')) return '[]';\n    if (systemText.includes('Pass 2 implementer')) return markers;\n    if (systemText.includes('senior product architect')) return protoArchitect;\n    if (systemText.includes('fixing build errors')) return markers;\n    if (systemText.includes('Generate a step-by-step plan')) return plan;\n    if (systemText.includes('Senior Tech Lead')) return tech;\n    if (systemText.includes('top-tier product founder') || systemText.includes('web developer designing a landing page')) return legacyArchitect;\n    if (systemText.includes('React') || systemText.includes('developer') || userText.includes('CURRENT USER REQUEST')) return stream ? artifact : markers;\n    return stream ? plan : analysis;\n  };\n"""
new = """  return (systemText, userText, stream) => {\n    // Route JSON-producing roles before the shared skeleton header: architect prompts\n    // also contain `SKELETON: Mobile App`, while coder prompts require FILE markers.\n    if (systemText.includes('fixing prototype quality gate failures')) return markers;\n    if (systemText.includes('Pass 2 critic')) return '[]';\n    if (systemText.includes('Pass 2 implementer')) return markers;\n    if (systemText.includes('senior product architect')) return protoArchitect;\n    if (systemText.includes('fixing build errors')) return markers;\n    if (systemText.includes('Generate a step-by-step plan')) return plan;\n    if (systemText.includes('Senior Tech Lead')) return tech;\n    if (systemText.includes('top-tier product founder') || systemText.includes('web developer designing a landing page')) return legacyArchitect;\n    if (systemText.includes('SKELETON: Mobile App')) return markers;\n    if (systemText.includes('React') || systemText.includes('developer') || userText.includes('CURRENT USER REQUEST')) return stream ? artifact : markers;\n    return stream ? plan : analysis;\n  };\n"""
if old not in text:
    raise SystemExit('mobile agent responder anchor not found')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
