- main [ref=e4]:
  - generic [ref=e5]:
    - generic [ref=e6]:
      - button "Home Dashboard" [ref=e7] [cursor=pointer]:
        - img [ref=e8]
      - generic [ref=e14]:
        - button "System Engine" [ref=e16] [cursor=pointer]:
          - img [ref=e17]
        - button "Трендовые ниши" [ref=e23] [cursor=pointer]:
          - img [ref=e24]
        - button "Projects" [ref=e28] [cursor=pointer]:
          - img [ref=e29]
        - button "Product Architect" [ref=e32] [cursor=pointer]:
          - img [ref=e33]
        - button "Figma Platinum" [ref=e39] [cursor=pointer]:
          - img [ref=e40]
        - button "Analytics" [ref=e47] [cursor=pointer]:
          - img [ref=e48]
        - button "Quality" [ref=e50] [cursor=pointer]:
          - img [ref=e51]
        - button "Code Studio" [ref=e55] [cursor=pointer]:
          - img [ref=e56]
        - button "DB Console" [ref=e61] [cursor=pointer]:
          - img [ref=e62]
        - button "Cloud & Backend — Coming Soon" [ref=e67]:
          - img [ref=e68]
        - button "Packaging & Ship — Coming Soon" [ref=e71]:
          - img [ref=e72]
        - button "Growth & Marketing — Coming Soon" [ref=e78]:
          - img [ref=e79]
    - generic [ref=e372]:
      - generic [ref=e373]:
        - generic [ref=e374]:
          - generic [ref=e375]: AIC-RG STUDIO PRO
          - button "New Project" [ref=e376] [cursor=pointer]:
            - img [ref=e377]
            - text: New Project
          - generic [ref=e379]: New Project
          - generic [ref=e380]: /
          - img [ref=e381]
          - generic [ref=e385]: main
          - generic [ref=e386]: ·
          - img [ref=e387]
          - generic [ref=e389]: "snap #0"
        - generic [ref=e391]: Not backed up
        - generic [ref=e392]:
          - generic [ref=e393]:
            - 'button "Theme: dark" [ref=e394] [cursor=pointer]'
            - 'button "Theme: medium" [ref=e395] [cursor=pointer]'
            - 'button "Theme: light" [ref=e396] [cursor=pointer]'
          - button "Settings" [ref=e397] [cursor=pointer]:
            - img [ref=e398]
          - button "D dev.local@aic-studio.test" [ref=e401] [cursor=pointer]:
            - generic [ref=e402]: D
            - generic [ref=e403]: dev.local@aic-studio.test
          - button "Backup to Cloud" [ref=e404] [cursor=pointer]:
            - img [ref=e405]
            - text: Backup to Cloud
      - generic [ref=e408]:
        - generic [ref=e410]:
          - generic [ref=e412]:
            - img [ref=e413]
            - generic [ref=e418]: AIC-RG Studio
            - generic [ref=e419]: Опишите идею ниже или выберите в сайдбаре
          - generic [ref=e420]:
            - generic [ref=e421]:
              - button "AUTO" [ref=e422]
              - button "APP" [ref=e423]
              - button "SUPER" [ref=e424]
              - button "ALL" [ref=e425]
              - button "История" [ref=e427]:
                - img [ref=e428]
                - text: История
              - button "Undo (Ctrl+Z)" [disabled] [ref=e433]:
                - img [ref=e434]
              - button "Redo (Ctrl+Shift+Z)" [disabled] [ref=e437]:
                - img [ref=e438]
            - generic [ref=e441]:
              - button "Attach / tools" [ref=e443]:
                - img [ref=e444]
              - textbox "Что строим сегодня?" [ref=e445]
              - button [disabled] [ref=e446]:
                - img [ref=e447]
        - generic [ref=e450]:
          - generic [ref=e451]:
            - generic [ref=e452]:
              - button "Preview" [ref=e453] [cursor=pointer]
              - button "Reasoning" [ref=e454] [cursor=pointer]
              - button "Code" [ref=e455] [cursor=pointer]
              - button "Design" [ref=e456] [cursor=pointer]
              - button "Analytics" [ref=e457] [cursor=pointer]
              - button "Security" [ref=e458] [cursor=pointer]
              - button "Cloud" [ref=e459] [cursor=pointer]
            - generic [ref=e460]:
              - button "Select" [ref=e461] [cursor=pointer]:
                - img [ref=e462]
                - text: Select
              - generic [ref=e464]:
                - button "Desktop Chrome" [ref=e465] [cursor=pointer]:
                  - img [ref=e466]
                - button "iPhone 16 Pro Max" [ref=e468] [cursor=pointer]:
                  - img [ref=e469]
                - button "Pixel 9 Pro" [ref=e471] [cursor=pointer]:
                  - img [ref=e472]
                - button "iPad Pro 13" [ref=e474] [cursor=pointer]:
                  - img [ref=e475]
              - generic [ref=e477]:
                - button "↑" [ref=e478] [cursor=pointer]
                - button "↓" [ref=e479] [cursor=pointer]
                - button "←" [ref=e480] [cursor=pointer]
                - button "⎘" [ref=e481] [cursor=pointer]
              - button "Export" [ref=e482] [cursor=pointer]:
                - img [ref=e483]
                - text: Export
              - button "Share" [ref=e486] [cursor=pointer]:
                - img [ref=e487]
                - text: Share
          - generic [ref=e495]:
            - generic [ref=e496]:
              - button [ref=e497] [cursor=pointer]:
                - img [ref=e498]
              - generic [ref=e501] [cursor=pointer]: 48%
              - button [ref=e502] [cursor=pointer]:
                - img [ref=e503]
              - button [ref=e507] [cursor=pointer]:
                - img [ref=e508]
            - iframe [ref=e517]:
              - generic [active] [ref=f1e1]: Build not found