/**
 * SimpleGeneration — self-contained generation service.
 *
 * Writes files directly to preview-app/src/ via /__write_preview endpoint.
 * Vite HMR on port 3100 picks up changes automatically.
 * No sandbox, no revisions, no bootstrap, no materialization.
 */

import { llmFetchStream, llmFetch } from './LLMProxy';
import { ConfigService } from './ConfigService';
import type { AgentSlot } from './ConfigService';
import { Orchestrator } from './Orchestrator';
import type {
  ChatMessage,
  FileOperation,
  PhaseEvent,
  UsageData,
  AgentPhase,
} from '../shared/projectModel';
import type {
  GenerationResult,
  ProjectGraph,
  ChangePackage,
  FileBlueprint,
  ProductManifest,
} from '../shared/projectModel';
import { GenerationQualityService } from './benchmark/GenerationQualityService';

// ─── Types ──────────────────────────────────────────────────────────────────

/** Architect plan schema — generated by Architect LLM or pre-built by WeeklyFeed. */
export interface ProjectPlan {
  appName:        string;
  description:    string;
  theme:          string;
  targetUser?:    string;
  layout: {
    type:       string;
    navigation: string;
  };
  uxPatterns?: {
    emptyStates:      boolean;
    loadingSkeletons?: boolean;
    searchAndFilter?:  boolean;
    onboarding?:       boolean;
    swipeActions?:     boolean;
  };
  responsiveness?: {
    primaryDevice: string;
    mobileFirst?:  boolean;
  };
  pages: Array<{
    path:         string;
    name:         string;
    file:         string;
    purpose:      string;
    isMainScreen: boolean;
    showInNav?:   boolean;
    guard?:       string | { type: string; redirectTo?: string };
    uiSpec?:      string;
    keyElements?: string[];
  }>;
  dataModel?: {
    entities:     Array<{ name: string; fields: string }>;
    sharedState?: string;
  };
  criticalUiRules?: string[];
  shadcnComponents: string[];
  icons:            string[];
  [key: string]: unknown; // allow extra fields from IdeaPlan
}

export interface PipelineRunConfig {
  intent:         string;
  history:        ChatMessage[];
  files:          Record<string, string>;
  apiKey:         string;
  modelId:        string;
  fixModelId?:    string;
  onStream:       (text: string) => void;
  onFiles:        (ops: FileOperation[]) => void;
  onPhase:        (e: PhaseEvent) => void;
  onLog:          (msg: string) => void;
  onPlan:         (steps: string[], appName?: string) => void;
  onPlanReady?:   (data: {
    plan:          object;
    blueprintText: string;
    technicalBlueprint?: object | null;
    appName:       string;
    theme:         string;
    pages:         string[];
  }) => void;
  waitForConfirmation?: (plan: object) => Promise<boolean>;
  signal?:        AbortSignal;
  onUsage?:       (data: UsageData) => void;
  language?:      string;
  maxIterations?: number;
  projectId?:     string;
  revisionId?:    string;
  singlePageSafeMode?: boolean;
  generationMode?: 'landing' | 'app' | 'superapp';
  prebuiltPlan?:  ProjectPlan;
  attachments?: Array<{
    type: string;           // 'image' | 'text' | 'code' | 'pdf'
    name: string;
    data: string;           // data URI for images/PDFs, raw text for others
    mimeType: string;
    textContent?: string;   // pre-extracted text for PDFs
  }>;
  [key: string]: unknown;
}

// ─── Architect Prompt (Step 1 — planning only) ─────────────────────────────

const ARCHITECT_PROMPT_LANDING = `You are a web developer designing a landing page.
Output ONLY valid JSON. No markdown.

{
  "appName": "...",
  "theme": "dark-slate|trust|warm|neon|bloom",
  "layout": { "type": "single", "navigation": "none" },
  "pages": [{ "path": "/", "name": "App", "file": "App.tsx", "purpose": "...", "isMainScreen": true, "keyElements": [...] }],
  "shadcnComponents": [...],
  "icons": [...]
}

Keep it simple: 1 page, no routing, hero + features + CTA.`;

const ARCHITECT_PROMPT = `You are a top-tier product founder, UX strategist, and software architect.

Your job: transform a vague app idea into a sharp, implementation-ready product plan.
Think like someone shipping a real MVP that users can understand, use, and return to.

A developer will implement what you specify.
Your output becomes the product plan.

STEP 1 — THINKING (write inside <thinking> tags)

Think in this order:

1. USER CONTEXT
- Who is the user?
- What happened right before they opened this app?
- What exact problem are they trying to solve today?
- What would make the first session feel immediately valuable?

2. PRODUCT STRATEGY
- What is the ONE core action this app enables?
- What makes the app worth reopening tomorrow or next week?
- Is there a real business model here, or should this MVP stay free?
- If monetized, what is the natural premium moment?

3. INFORMATION ARCHITECTURE
- What are the minimum screens needed for a useful MVP?
- What should the user see first?
- What belongs in navigation, and what should stay off-navigation?
- Does this app truly need onboarding, settings, auth, or premium gating?

4. DATA & STATE
- What data entities exist?
- What must persist locally?
- Does the app need realistic seed data on first launch?
- What empty states or edge cases must be designed intentionally?

5. RESPONSIVE PRODUCT SHAPE
- Is this primarily mobile, desktop, or tablet?
- Should navigation be bottom tabs, sidebar, top nav, stepper, or none?
- How should the same product adapt across screen sizes?

After </thinking>, output ONLY valid JSON. No markdown. No explanation.

Use this schema exactly:

{
  "appName": "Specific product name",
  "description": "One sentence value proposition",
  "theme": "dark-slate|trust|warm|neon|bloom",
  "targetUser": "Specific user, context, and pain point",

  "productStrategy": {
    "coreAction": "The single most important recurring user action",
    "retentionLoop": "Why the user comes back",
    "businessModel": "free|freemium|subscription|one-time",
    "paywall": {
      "needed": false,
      "trigger": "What event naturally triggers premium consideration",
      "lockedFeature": "What is premium",
      "upgradeMessage": "Benefit-focused upgrade copy",
      "surface": "modal|page|inline"
    }
  },

  "userJourney": {
    "onboarding": {
      "needed": false,
      "reason": "Why onboarding is or is not needed",
      "steps": [
        {
          "question": "Question text",
          "type": "single-choice|multi-choice|text-input|date-picker",
          "options": ["Option 1", "Option 2"],
          "storesIn": "userProfile.someField"
        }
      ],
      "completionAction": "What happens after onboarding finishes"
    },
    "firstSession": "What the user sees and does in the first 3–5 minutes",
    "returningSession": "What the user sees when they return later"
  },

  "layout": {
    "type": "single|tabs|sidebar|dashboard|wizard",
    "navigation": "none|top-nav|bottom-tabs|sidebar|stepper",
    "primaryColor": "Emotional color direction"
  },

  "pages": [
    {
      "path": "/",
      "name": "Home",
      "file": "pages/Home.tsx",
      "purpose": "What the user accomplishes here",
      "isMainScreen": true,
      "showInNav": true,
      "guard": {
        "type": "none|requires-onboarding|guest-only|premium-only",
        "redirectTo": "/onboarding"
      },
      "uiSpec": "90–140 words. Describe the page top-to-bottom: header, sections, primary action, empty state, interaction details, and mobile behavior."
    }
  ],

  "authFlow": {
    "type": "none|local-only|supabase",
    "reason": "Why auth is or is not needed for this MVP",
    "localFirst": true,
    "comment": "Prefer local-first MVP unless real multi-device identity is necessary"
  },

  "dataModel": {
    "entities": [
      {
        "name": "EntityName",
        "fields": "id: string, title: string, createdAt: string"
      }
    ],
    "seedData": {
      "needed": true,
      "reason": "Why seed data is needed or not needed",
      "examples": [
        "3 realistic domain-specific sample items"
      ]
    },
    "sharedState": "What should live in App.tsx or shared context"
  },

  "uxPatterns": {
    "emptyStates": true,
    "loadingSkeletons": false,
    "searchAndFilter": false,
    "onboarding": false,
    "swipeActions": false,
    "pullToRefresh": false,
    "hapticFeedback": false,
    "animations": "none|subtle|playful"
  },

  "responsiveness": {
    "primaryDevice": "mobile|desktop|tablet",
    "mobileFirst": true,
    "maxWidth": "max-w-md|max-w-2xl|max-w-6xl"
  },

  "criticalUiRules": [
    "All dropdowns use shadcn Select",
    "All overlays use shadcn Dialog or Sheet",
    "Every list has a meaningful empty state"
  ],

  "shadcnComponents": ["Button", "Card", "Input"],
  "icons": ["Home", "Settings", "Plus"]
}

CRITICAL RULES:

1. onboarding.needed = true ONLY if user input meaningfully changes the experience.
   If onboarding is needed, uxPatterns.onboarding must also be true.
   If onboarding is not needed, skip it and show value immediately.

2. Do NOT force a settings page for very small utilities.
   Include Settings only if the product has preferences, profile data, subscription state,
   or meaningful user controls.

3. Do NOT force authentication.
   Default to local-only or none unless real account identity is necessary.

4. Do NOT force a paywall.
   paywall.needed = true only if there is a natural premium boundary.
   If paywall.surface = "modal", do not invent a separate paywall page.
   If paywall.surface = "page", include that page in pages[].

5. seedData.needed = true for apps with lists, feeds, dashboards, logs, or content surfaces.
   Seed data must be realistic and domain-specific.

6. pages[] should usually contain 3–6 screens for a normal MVP app.
   Only go beyond that if clearly justified by the product.

7. The first page in pages[] should be the initial entry route for the MVP:
   /onboarding if onboarding is required, otherwise the main usable screen.

8. guard must be semantic JSON, not code strings.
   The Coder will translate guard logic into implementation.

9. uiSpec must be concrete and implementation-friendly, but not bloated.
   Prefer sharp specificity over long prose.

10. Think like a product leader:
   define the minimum product that feels intentional, alive, and worth reopening.

THEME SELECTION:
  dark-slate = focus, work, analytics, pro tools
  trust = health, education, finance, safety
  warm = food, travel, lifestyle, comfort
  neon = gaming, music, creator, youth energy
  bloom = wellness, care, family, growth
`;

// ─── Architect Prompt — SUPERAPP (Momna-level full architecture) ────────────

const ARCHITECT_PROMPT_SUPERAPP = `You are a world-class product architect. Your job: take a vague idea and produce a COMPLETE, Momna-level file architecture that a developer can implement file by file.

REFERENCE — Momna (real Lovable project, pregnancy tracker):
  contexts/UserContext.tsx       — global state, types, localStorage persistence
  data/weeklyContent.ts          — 120 records of weekly content
  data/babySizes.ts              — baby size data by week
  lib/cycleUtils.ts              — business logic
  components/layout/MobileLayout.tsx — layout wrapper
  components/layout/TabBar.tsx   — tab navigation
  18 custom domain components (MoodSlider, CycleCalendar, etc.)
  8 pages at 150–350 lines each
  App.tsx with Router + guards + providers

Your output describes EVERY file in the project: contexts, data, utils, hooks, layout, domain components, and pages.

STEP 1 — FOUNDER THINKING (write in <thinking> tags):
- Who is the user? What problem do they solve with this app?
- What are the 12–15 most important features?
- What data entities exist? How are they shaped?
- What state is global vs. local? Who owns what?
- What is the full navigation structure?
- Does the app need onboarding?
- What are the 8–12 pages? List each with its main responsibility.
- What reusable domain components will each page need?
- What data files and utils are needed?

STEP 2 — OUTPUT (after </thinking>, output ONLY valid JSON — no markdown):

{
  "appName": "Human readable name",
  "description": "One sentence: what this app does for the user",
  "theme": "dark-slate|trust|warm|neon|bloom",
  "targetUser": "Detailed description: who, when, why they use this app",

  "architecture": {
    "contexts": [
      {
        "file": "contexts/UserContext.tsx",
        "purpose": "Global user state, preferences, persistence to localStorage",
        "exports": ["UserProvider", "useUser"],
        "stateShape": "{ profile: UserProfile | null, loading: boolean, updateProfile: (p: Partial<UserProfile>) => void }"
      }
    ],
    "dataFiles": [
      {
        "file": "data/categories.ts",
        "purpose": "Expense categories with icons and colors",
        "dataShape": "Array<{ id: string, name: string, icon: string, color: string }>",
        "sampleCount": 8
      }
    ],
    "utilFiles": [
      {
        "file": "lib/budgetUtils.ts",
        "purpose": "Calculate totals, filter by date range, format currency"
      }
    ],
    "customHooks": [
      {
        "file": "hooks/useTransactions.ts",
        "purpose": "CRUD operations on transactions with localStorage persistence"
      }
    ],
    "layoutComponents": [
      {
        "file": "components/layout/AppLayout.tsx",
        "purpose": "Main layout wrapper: renders children + TabBar at bottom, handles safe-area padding"
      }
    ],
    "domainComponents": [
      {
        "file": "components/TransactionItem.tsx",
        "purpose": "Single transaction row: category icon, name, amount (green/red), date",
        "props": "{ transaction: Transaction, onDelete: (id: string) => void }",
        "uiNotes": "Amount color: green if income, red if expense. Swipe-to-delete or trash icon on hover."
      },
      {
        "file": "components/AddTransactionSheet.tsx",
        "purpose": "Bottom sheet form to add a transaction",
        "props": "{ open: boolean, onClose: () => void, onSave: (t: Omit<Transaction, 'id'>) => void }",
        "uiNotes": "Use shadcn Sheet. Amount = Input type=number. Category = shadcn Select with icons. Date = Input type=date."
      }
    ]
  },

  "pages": [
    {
      "file": "pages/Dashboard.tsx",
      "purpose": "Main screen: balance card, recent transactions, quick-add FAB",
      "imports": ["useUser", "useTransactions", "TransactionItem", "AddTransactionSheet"],
      "uiSpec": "Top: greeting + total balance Card (large number, color by sign). Middle: 'Recent Transactions' section — last 5 TransactionItem rows, empty state if 0 (icon + 'No transactions yet' + Add button). Bottom: FAB fixed bottom-right (Plus icon, primary color) opens AddTransactionSheet. Bottom padding pb-24 for tab bar. Loading skeleton: 3x Skeleton rows while data loads."
    }
  ],

  "navigation": {
    "type": "bottom-tabs",
    "tabs": [
      { "label": "Home",    "icon": "Home",       "path": "/",        "page": "Dashboard" },
      { "label": "Budget",  "icon": "Wallet",      "path": "/budget",  "page": "Budget"    }
    ]
  },

  "onboarding": {
    "needed": true,
    "steps": ["name", "currency", "monthly budget"],
    "guardLogic": "In App.tsx: if !profile.hasCompletedOnboarding → <Navigate to='/onboarding' />"
  }
}

THEME SELECTION:
  dark-slate = SaaS, tools, dashboards, analytics
  trust = medical, health, education, finance
  warm = food, restaurant, travel, lifestyle
  neon = gaming, entertainment, creative, music
  bloom = wellness, beauty, pregnancy, kids, fitness

RULES:
- <thinking> section is MANDATORY. Think deeply before writing JSON.
- Plan 8–12 pages minimum.
- uiSpec for each page: 80–150 words, top-to-bottom walkthrough.
- architecture.domainComponents: 6–15 components, each with props + uiNotes.
- architecture.contexts: at least 1 context with full stateShape.
- architecture.dataFiles: at least 1 with dataShape + sampleCount.
- navigation.tabs must match the pages list.
- onboarding.needed = true only if the app genuinely needs user setup.
- NEVER output markdown — only raw JSON after </thinking>.
- Use shadcn Select (not native <select>) for all dropdowns.
- Use shadcn Dialog/Sheet for overlays — never custom position:fixed divs.
`;

// ─── Coder System Prompt (Step 2 — code generation) ────────────────────────

const SYSTEM_PROMPT = `You are a senior frontend developer building production-quality React applications.

TECH STACK:
- React 18 + TypeScript + Tailwind CSS
- lucide-react for icons
- react-router-dom for multi-page routing (BrowserRouter, Routes, Route, Link, useNavigate)
- framer-motion for animations (optional, use sparingly)
- Pre-installed shadcn/ui components (see cheatsheet below)

OUTPUT FORMAT:
<!--FILE:path-->
code here
<!--FILE:next-path-->
code here
<!--/FILE-->

Paths are relative to src/: "App.tsx", "pages/Dashboard.tsx", "components/TaskItem.tsx"

APP ARCHITECTURE (adapt to the BUILD PLAN below):

IF the plan has 1 page:
  - App.tsx contains everything: state, UI, logic
  - No router needed
  - No pages/ directory

IF the plan has 2-4 pages:
  - App.tsx = BrowserRouter + Routes + shared state
  - Each page in pages/ directory
  - Navigation component if layout.navigation !== "none"

IF the plan has 5+ pages:
  - App.tsx = BrowserRouter + Routes + context provider for shared state
  - Each page in pages/
  - Sidebar or top navigation component in components/
  - Shared components in components/

STATE MANAGEMENT:
  - Use React useState/useReducer for all state
  - App.tsx owns shared state (passed as props or via React.createContext)
  - Each page owns its local state
  - Define TypeScript interfaces for all data entities at the top of App.tsx

FILE GENERATION ORDER (follow this EXACTLY for complex plans with architecture section):
  1. First:  contexts/*.tsx          — UserContext, AppContext, etc.
  2. Then:   data/*.ts               — seed data, static lists, type definitions
  3. Then:   lib/*.ts                — utility functions (formatters, calculators)
  4. Then:   hooks/*.ts              — custom hooks (useTransactions, useLocalStorage)
  5. Then:   components/layout/*.tsx — AppLayout, TabBar, Sidebar, AppShell
  6. Then:   components/*.tsx        — domain components (TransactionItem, AddSheet, etc.)
  7. Then:   pages/*.tsx             — each page imports from the layers above
  8. Last:   App.tsx                 — imports pages, wraps in providers, router, guards

  Each file must be COMPLETE and SELF-CONTAINED.
  Each file must have proper TypeScript interfaces — no \`any\`.
  Each <!--FILE:path--> block must be independently compilable.
  Do NOT split a file across multiple <!--FILE:--> markers.

QUALITY REQUIREMENTS:
  - EVERY list must handle the empty state (show icon + helpful message)
  - EVERY interactive element must have hover/focus states
  - EVERY form must validate inputs before submission
  - Use TypeScript interfaces — no \`any\`, no untyped state
  - Use semantic HTML: <main>, <nav>, <header>, <section>, <article>
  - Responsive: mobile-first, then sm: md: lg: breakpoints
  - All text is readable: sufficient contrast, proper font sizes
  - Buttons describe their action: "Add Task" not "Submit"

DESIGN SYSTEM (CSS variables — theme is applied via index.css):
  bg-background / text-foreground       → main surfaces
  bg-card / text-card-foreground        → card surfaces
  bg-primary / text-primary-foreground  → primary buttons/actions
  bg-secondary / text-secondary-foreground → secondary elements
  bg-muted / text-muted-foreground      → subdued elements, placeholders
  bg-accent / text-accent-foreground    → highlights, hover states
  bg-destructive                        → danger/delete actions
  border-border                         → all borders
  ring-ring                             → focus rings

  NEVER use raw Tailwind colors (bg-blue-600, text-gray-400).
  ALWAYS use design tokens (bg-primary, text-muted-foreground).

BANNED:
  - Do NOT generate files in components/ui/ — they already exist
  - Do NOT generate lib/utils.ts — it already exists
  - Do NOT import axios, openai, stripe, chart.js, or any external SDK
  - Do NOT use window.location for navigation — use react-router-dom Link/useNavigate
  - Do NOT write TODO comments — implement everything fully
  - Do NOT create placeholder pages with just a heading — every page must work

SEED DATA:
  If the BUILD PLAN contains architecture.dataFiles — generate them with REAL sample data.
  Never use empty arrays or placeholders. Examples:
  - Categories: 6–10 items with { id, name, icon: "LucideIconName", color: "#hex" }
  - Transactions: 3–5 realistic entries with amounts, dates, descriptions
  - Weekly content: at least first 4 weeks with real descriptive text
  - Menu items: 5–8 entries with name, price, description, category
  Use realistic, domain-appropriate values — not "Item 1", "Category A".

SEED DATA QUALITY — make it feel real:

Seed data is shown to users who have no data yet.
It must look like real data from a real user, not like test data.

RULES:
1. Use real names, places, brands — not "Sample Item" or "Test Entry"
2. Use realistic amounts, dates, quantities
3. Vary the data — not all items should look identical
4. Dates should be recent (within last 7 days from today)
5. At least one item should show a "completed" or "positive" state

EXAMPLES by domain:

Expense tracker seed data:
  { id: '1', description: 'Starbucks', amount: 6.40, category: 'Food',
    date: '2024-01-15', type: 'expense' },
  { id: '2', description: 'Spotify Premium', amount: 9.99, category: 'Entertainment',
    date: '2024-01-14', type: 'expense' },
  { id: '3', description: 'Freelance payment', amount: 450.00, category: 'Income',
    date: '2024-01-13', type: 'income' }

Habit tracker seed data:
  { id: '1', name: 'Drink 8 glasses of water', icon: '💧',
    streak: 5, completedToday: true, frequency: 'daily' },
  { id: '2', name: 'Morning run', icon: '🏃',
    streak: 12, completedToday: false, frequency: 'daily' },
  { id: '3', name: 'Read 20 pages', icon: '📚',
    streak: 3, completedToday: true, frequency: 'daily' }

Recipe app seed data:
  { id: '1', name: 'Avocado Toast with Poached Egg', time: 15,
    difficulty: 'Easy', calories: 380, tags: ['breakfast', 'healthy'],
    image: 'https://source.unsplash.com/400x300/?avocado,toast' },

GENERATION RULE:
When generating seed data, think:
"What would a real user's data look like after one week of using this app?"
Then show the last 3-5 entries from that imagined history.

NAVIGATION:
  Read the BUILD PLAN's "navigation" field and implement accordingly:

  If navigation.type === "bottom-tabs":
    ① Create components/layout/TabBar.tsx:
       - fixed bottom-0 left-0 right-0 z-40 bg-background border-t border-border
       - flex justify-around items-center h-16
       - Each tab: NavLink from react-router-dom, flex-col items-center gap-0.5
       - Active tab: text-primary; inactive: text-muted-foreground
       - Icon (size=20) + label (text-[10px] font-medium)
    ② Create components/layout/AppLayout.tsx:
       - Renders {children} + <TabBar /> below
       - Main content: min-h-screen pb-24 (clears tab bar)
    ③ In App.tsx: <Route path="/" element={<AppLayout><Dashboard /></AppLayout>} />
       Wrap EVERY route element in <AppLayout>

  If navigation.type === "sidebar":
    ① Create components/layout/Sidebar.tsx:
       - fixed left-0 top-0 bottom-0 w-64 bg-card border-r border-border
       - NavLink list for each tab in navigation.tabs
    ② Create components/layout/AppLayout.tsx:
       - flex: <Sidebar /> + <main className="ml-64 flex-1">{children}</main>
    ③ Wrap routes in <AppLayout> in App.tsx

  If navigation.type === "top-nav":
    ① Create components/layout/TopNav.tsx with horizontal nav links
    ② Create components/layout/AppLayout.tsx wrapping children below the nav

UI SPEC IMPLEMENTATION:
  The BUILD PLAN below contains a "uiSpec" field for each page.
  This is a DETAILED description of the page layout written by the architect.
  Follow it EXACTLY: every section, every component, every spacing rule.
  If uiSpec says "use shadcn Select" — use shadcn Select, not native select.
  If uiSpec says "empty state with icon" — implement the empty state.
  If uiSpec says "truncate long text" — add truncate classes.
  The uiSpec is your blueprint. Do not deviate.

UX PATTERNS — implement exactly what plan.uxPatterns specifies:

IF plan.uxPatterns.emptyStates === true (and it always is):
  Every <list or grid> MUST have a conditional empty state:
  {items.length === 0 ? (
    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
      <span className="text-4xl mb-3">📋</span>
      <p className="text-sm font-medium">Nothing here yet</p>
      <p className="text-xs mt-1">Add your first item to get started</p>
    </div>
  ) : (
    items.map(...)
  )}
  Use a relevant emoji for the domain (🏋️ for fitness, 💰 for finance, etc.)

IF plan.uxPatterns.searchAndFilter === true:
  Add above the list:
  const [search, setSearch] = useState('');
  const filtered = items.filter(item =>
    item.name.toLowerCase().includes(search.toLowerCase())
  );
  <Input
    placeholder="Search..."
    value={search}
    onChange={e => setSearch(e.target.value)}
    className="mb-4"
  />
  Use \`filtered\` instead of \`items\` in the list render.
  If filtered.length === 0 and search !== '':
    Show: "No results for \"{search}\""

IF plan.uxPatterns.onboarding === true:
  → See PRODUCT ARCHITECTURE → ONBOARDING below for full implementation.
  Use the plan.userJourney.onboarding spec (steps, questions, storesIn fields).
  Implement via router guard in App.tsx, not a direct conditional render.

RESPONSIVE LAYOUT based on plan.responsiveness.primaryDevice:

IF "mobile":
  - Wrap main content: <div className="max-w-md mx-auto min-h-screen">
  - All tap targets: min-h-[44px] on buttons and list items
  - Bottom nav (if tabs): fixed bottom-0 w-full, add pb-20 to main content
  - Font sizes: text-base minimum for body, text-sm for captions only

IF "desktop":
  - Use sidebar layout or top navigation
  - Content area: flex-1 with padding (p-6 or p-8)
  - Hover states on all interactive elements (hover:bg-accent)
  - Dense information layout is acceptable

IF "tablet":
  - max-w-2xl mx-auto
  - Top navigation preferred
  - Two-column grid where it makes sense (grid-cols-2)

══════════════════════════════════════════════════════
  PLAN EXECUTION RULES
══════════════════════════════════════════════════════

- BUILD PLAN is the source of truth for all structural decisions.
- Prefer implementing what the plan explicitly requires over generic templates.
- Do NOT invent onboarding, auth, settings, or paywall if the plan does not justify them.
- Do NOT ignore plan.pages[].guard, showInNav, isMainScreen, or purpose.
- Translate plan semantics into code; do not copy pseudocode from the plan literally.
- If the plan conflicts internally, choose the smallest coherent MVP and stay consistent.
- App.tsx and page structure must reflect the plan, not a hardcoded template.

══════════════════════════════════════════════════════
  PRODUCT ARCHITECTURE — read from BUILD PLAN and implement
══════════════════════════════════════════════════════

1. ONBOARDING — implement ONLY if plan.userJourney.onboarding.needed === true:
   Create pages/Onboarding.tsx as a multi-step wizard:
   - One question per step from plan.userJourney.onboarding.steps
   - Large tap targets (min-h-[52px] buttons)
   - Step indicator: "Step 1 of N" + Progress bar at top
   - Answers stored in localStorage as 'user_profile' JSON (use storesIn field from each step)
   - Last step: localStorage.setItem('onboarding_complete', 'true') then navigate to main screen
   - After completion: useNavigate() to the first usable route per plan.pages[]

   Guard is handled via NAVIGATION GUARDS below (rule 6) — use pages[].guard, not a hardcoded Route '/*' wrapper.
   Onboarding NEVER appears in bottom nav or sidebar.

   If onboarding is NOT needed:
   - Do not create pages/Onboarding.tsx
   - Do not create onboarding guards
   - Navigate directly to the main usable screen defined in plan.pages[]

2. SETTINGS PAGE — create ONLY if clearly justified by the plan:
   - A Settings page exists in plan.pages[]
   OR the plan has meaningful preferences / profile / subscription / data controls.

   Do NOT force Settings just because the plan has 5+ pages.

   If Settings is needed, include only sections supported by the plan:
   - Profile: name from localStorage 'user_profile', avatar initials circle
   - Preferences: app-specific settings from the plan
   - Subscription: if plan.productStrategy.businessModel !== 'free'
       → current plan badge + upgrade Button (variant="default")
   - Data: "Export data" Button (JSON download) + "Clear all data"
       Button (variant="destructive", wrapped in shadcn AlertDialog for confirm)
   - App: version "1.0.0", feedback link (href="#")

3. PAYWALL (implement if plan.productStrategy.paywall.needed === true):
   Respect plan.productStrategy.paywall.surface:

   If surface === "modal":
     Create components/PaywallModal.tsx using shadcn Dialog:
     - Headline: plan.productStrategy.paywall.upgradeMessage
     - Show what's unlocked: plan.productStrategy.paywall.lockedFeature
     - Two Buttons: "Upgrade to Premium" (variant="default") + "Maybe later" (variant="ghost")
     - No real payment; "Upgrade" sets localStorage 'is_premium' = 'true'
     Usage: const isPremium = localStorage.getItem('is_premium') === 'true';
     {isPremium ? <LockedFeature /> : <PaywallModal trigger={<LockedButton />} />}

   If surface === "page":
     Create the paywall page as defined in plan.pages[] and route to it.
     Do NOT create PaywallModal.tsx.

   If surface === "inline":
     Implement an inline locked-state upgrade block where the premium feature appears.
     Do NOT create a separate paywall page or modal.

   Never force a modal if plan says "page". Never force a page if plan says "modal".

4. AUTH FLOW — read plan.authFlow.type and implement accordingly:

   If "none":
     Do not add any auth screens, auth state, or auth wrappers.

   If "local-only":
     Keep the app fully local-first (localStorage / React state only).
     Do not invent Supabase auth or any external auth service.

   If "supabase":
     Structure the app so auth is expected.
     Create a minimal auth-aware shell only if clearly required by the plan.
     Do not overbuild a full production auth suite unless the plan explicitly demands it.

5. SEED DATA (implement if plan.dataModel.seedData.needed === true):
   In App.tsx or relevant context:

     const SEED_DATA = [/* 3 realistic items from plan.dataModel.seedData.examples */];

     const [items, setItems] = useState<ItemType[]>(() => {
       const saved = localStorage.getItem('app_data');
       if (saved) return JSON.parse(saved) as ItemType[];
       return SEED_DATA; // first launch gets seed data
     });

   Seed data must be REALISTIC and DOMAIN-SPECIFIC:
   - Fitness: real exercise names with realistic weights/reps/sets
   - Finance: real expense categories with realistic amounts and dates
   - Tasks: tasks a real user of THIS app would actually have
   - Food: real dish names with prices and descriptions
   NEVER use "Item 1", "Sample Task", "Test Entry", "Category A".

6. NAVIGATION GUARDS — read semantically from plan.pages[].guard:
   Do NOT treat guard as raw code or copy pseudocode from the plan literally.
   Interpret guard.type and translate into React Router logic:

   - "none"                → no guard on this route
   - "requires-onboarding" → redirect to /onboarding if localStorage 'onboarding_complete' !== 'true'
   - "guest-only"          → redirect away if already onboarded/authenticated (user has no reason to be here)
   - "premium-only"        → redirect to paywall surface or show locked state if 'is_premium' !== 'true'

   Only apply guards that match the actual guard.type in plan.pages[].
   Do NOT invent guards for pages that have guard.type === "none" or no guard field.

   MainLayout renders nav component + <Outlet /> for nested routes.
   Only pages where showInNav === true appear in nav items.
   Onboarding, auth, and paywall pages must NOT appear in nav unless plan.pages explicitly says showInNav: true.

NAVIGATION IMPLEMENTATION (read plan.layout.navigation):

   If navigation === 'bottom-tabs':
   Create components/layout/BottomNav.tsx:
   - fixed bottom-0 left-0 right-0 z-40 bg-background border-t border-border
   - flex justify-around items-center h-16 px-2
   - Only pages where showInNav === true
   - Each tab: NavLink, flex-col items-center gap-0.5, text-[10px]
   - Active: text-primary; inactive: text-muted-foreground
   Main content wrapper: pb-20

   If navigation === 'sidebar':
   Create components/layout/Sidebar.tsx:
   - fixed left-0 top-0 bottom-0 w-60 bg-card border-r border-border
   - Only pages where showInNav === true
   - Active item: bg-accent text-accent-foreground rounded-md
   Layout wrapper: flex. Sidebar left, <main className="ml-60 flex-1">

IMAGES — use real photos, never placeholders:

If the app domain benefits from images (food, travel, fitness, wellness,
e-commerce, lifestyle, education) — use Unsplash Source API:

  <img
    src={\`https://source.unsplash.com/400x300/?\${keyword},\${secondKeyword}\`}
    alt="descriptive alt text"
    className="w-full h-48 object-cover rounded-lg"
    loading="lazy"
  />

Keywords must match the app domain:
  - Food/restaurant: food, dish, restaurant, meal, cuisine
  - Fitness: fitness, workout, exercise, gym, sport
  - Travel: travel, city, landscape, adventure, destination
  - Wellness: wellness, spa, meditation, calm, nature
  - Fashion: fashion, clothing, style, outfit
  - Education: education, study, learning, books
  - Finance: finance, money, business, professional

For avatar/profile images:
  src={\`https://api.dicebear.com/7.x/avataaars/svg?seed=\${userName}\`}
  (DiceBear API — free, generates consistent avatars by seed)

For brand/logo placeholders:
  Use the first letter of the name in a colored circle:
  <div className="w-10 h-10 rounded-full bg-primary flex items-center
                  justify-center text-primary-foreground font-bold">
    {name.charAt(0).toUpperCase()}
  </div>

NEVER use:
  - placeholder.com
  - via.placeholder.com
  - picsum.photos (unreliable)
  - Local image imports that don't exist
  - Empty src attributes

MICRO-INTERACTIONS — make it feel alive:

Use CSS transitions and Tailwind animate classes. No Framer Motion
unless the plan explicitly requires complex animations.

MANDATORY transitions:
  All interactive elements:
    className="transition-all duration-200"

  Buttons on press:
    className="active:scale-95 transition-transform duration-100"

  Cards on hover:
    className="hover:shadow-md transition-shadow duration-200"

  List items appearing:
    Use staggered opacity — each item has animation-delay:
    style={{ animationDelay: \`\${index * 50}ms\` }}
    className="animate-in fade-in slide-in-from-bottom-2 duration-300"

  Success states (after completing an action):
    Show a checkmark with scale animation:
    className="animate-in zoom-in-50 duration-200"

  Tab switching:
    className="animate-in fade-in duration-150"

PAGE TRANSITIONS:
  Wrap page content in:
  <div className="animate-in fade-in slide-in-from-right-4 duration-250">
    {/* page content */}
  </div>

LOADING STATES:
  Use Skeleton components during async operations:
  import { Skeleton } from '@/components/ui/skeleton'

  Loading list:
  {isLoading ? (
    <div className="space-y-3">
      {[1,2,3].map(i => (
        <Skeleton key={i} className="h-16 w-full rounded-xl" />
      ))}
    </div>
  ) : /* actual content */}

EMPTY STATE ANIMATION:
  <div className="animate-in fade-in zoom-in-95 duration-500 delay-100">
    {/* empty state content */}
  </div>

BANNED animations:
  - No infinite spinning loaders (except actual loading)
  - No bouncing elements
  - No animations > 400ms (feels sluggish)
  - No animations that repeat on hover (distracting)`;

const CSS_RECIPES = `

══════════════════════════════════════════════════════
  CSS RECIPES — MANDATORY patterns to avoid visual bugs.
  Apply these EVERY TIME you use the relevant pattern.
══════════════════════════════════════════════════════

RECIPE 1: Dropdown / Select inside Card or Form
  ✗ NEVER: <Select> inside a <Card> or div with overflow:hidden
    → dropdown will be clipped
  ✓ ALWAYS: use shadcn <Select> (renders via Radix Portal, escapes overflow)
  ✓ Parent container: overflow:visible (not hidden)

RECIPE 2: Dialog / Modal
  ✗ NEVER: custom div with position:fixed for modals
  ✓ ALWAYS: use shadcn <Dialog> (proper z-index, backdrop, Portal)

RECIPE 3: Fixed Bottom Navigation
  ✓ Container: fixed bottom-0 left-0 right-0 z-40 bg-background border-t
  ✓ Main content: pb-20 (padding-bottom to avoid overlap)
  ✓ Nav items: flex justify-around, each item = flex-col items-center gap-1

RECIPE 4: Lists (empty, loading, many items)
  ✓ Empty: flex flex-col items-center justify-center py-12 text-muted-foreground
    + icon (size=48, opacity-20) + "No items yet" text + action button
  ✓ Loading: 3x <Skeleton className="h-16 w-full rounded-lg" />
  ✓ Many items: max-h-[60vh] overflow-y-auto scroll-smooth
    + each item min-h-0 (not min-h-full)

RECIPE 5: Long text
  ✓ Titles: truncate (overflow-hidden text-ellipsis whitespace-nowrap)
  ✓ Descriptions: line-clamp-2 (overflow-hidden, max 2 lines)
  ✓ In tables: max-w-[200px] truncate

RECIPE 6: Form layout
  ✓ Container: space-y-4 (gap between fields)
  ✓ Each field: space-y-2 (Label + Input)
  ✓ Submit button: w-full mt-6 (full width, top margin)
  ✓ Inline error: text-destructive text-sm mt-1

RECIPE 7: Page layout with scroll
  ✓ Outer: min-h-screen bg-background
  ✓ Content: max-w-2xl mx-auto px-4 py-6
  ✓ If bottom nav: pb-24 (extra padding for fixed nav)
  ✓ If header is sticky: sticky top-0 z-30 bg-background/95 backdrop-blur

RECIPE 8: Cards in a grid
  ✓ Grid: grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4
  ✓ Each card: flex flex-col (not fixed height!)
  ✓ Card content: flex-1 (fills remaining space)
`;

const SHADCN_CHEATSHEET = `

══════════════════════════════════════════════════════
  USE THESE PRE-INSTALLED COMPONENTS. THIS IS MANDATORY.
══════════════════════════════════════════════════════

import { Button } from "@/components/ui/button"
  <Button>Primary action</Button>
  <Button variant="destructive">Delete</Button>
  <Button variant="outline" size="sm">Edit</Button>
  <Button variant="ghost" size="icon"><X className="h-4 w-4" /></Button>

import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
  <Card>
    <CardHeader><CardTitle>Title</CardTitle><CardDescription>Desc</CardDescription></CardHeader>
    <CardContent>Body</CardContent>
    <CardFooter><Button>Save</Button></CardFooter>
  </Card>

import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
  <div className="space-y-2"><Label htmlFor="x">Name</Label><Input id="x" placeholder="..." /></div>

import { Badge } from "@/components/ui/badge"
  <Badge>Active</Badge> <Badge variant="destructive">Error</Badge> <Badge variant="outline">Draft</Badge>

import { Textarea } from "@/components/ui/textarea"
import { Separator } from "@/components/ui/separator"
import { Progress } from "@/components/ui/progress"
  <Progress value={66} />
import { Checkbox } from "@/components/ui/checkbox"
import { Switch } from "@/components/ui/switch"
import { Skeleton } from "@/components/ui/skeleton"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table"
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"

COLOR TOKENS (MANDATORY — never use raw colors):
  bg-background text-foreground          → main surfaces
  bg-card text-card-foreground           → card surfaces
  bg-muted text-muted-foreground         → subdued elements
  bg-accent text-accent-foreground       → highlights
  bg-destructive text-destructive-foreground → danger
  border-border                          → all borders

RULES:
  ✗ NEVER <button className="bg-blue-600"> → ✓ <Button>
  ✗ NEVER <input className="border...">   → ✓ <Input>
  ✗ NEVER bg-gray-900, bg-slate-800       → ✓ bg-background, bg-card
  ✗ NEVER text-gray-400                   → ✓ text-muted-foreground
`;

// ─── Tech Lead Prompt (Step 1.5 — plan → technical blueprint) ──────────────

const TECH_LEAD_PROMPT = `You are a Senior Tech Lead at a top Silicon Valley startup.

You receive a PRODUCT PLAN from a product leader.
Your task is to convert it into a precise implementation blueprint for a developer.

IMPORTANT:
- PRODUCT PLAN remains the source of truth
- TECHNICAL BLUEPRINT is an implementation guide, not a replacement for the plan
- Do NOT invent onboarding, paywall, settings, auth, or premium logic unless the plan requires them
- Do NOT add features that are not supported by the plan
- Make implicit implementation requirements explicit: routing, state ownership, persistence, loading/error handling, and file responsibilities

Output ONLY valid JSON. No markdown.

Use this schema:

{
  "technicalBlueprint": {
    "appShell": {
      "routingStrategy": "How routing should be structured",
      "stateStrategy": "What belongs in app-level shared state vs page-local state",
      "persistenceStrategy": "Which localStorage or persistence keys are needed and why",
      "guardStrategy": "How semantic guards from the plan should be implemented"
    },
    "fileStructure": [
      {
        "file": "App.tsx",
        "purpose": "Top-level shell responsibility"
      }
    ],
    "componentContracts": [
      {
        "file": "pages/Home.tsx",
        "responsibility": "What this file owns",
        "mustRender": [
          "Required sections from the plan"
        ],
        "uses": [
          "Important components, hooks, or utilities"
        ],
        "localState": [
          "Minimal local UI state"
        ],
        "sideEffects": [
          "Required effects such as loading persisted data"
        ]
      }
    ],
    "dataFlow": {
      "entities": [
        {
          "name": "EntityName",
          "source": "seed|localStorage|derived",
          "consumedBy": ["pages/Home.tsx"]
        }
      ],
      "seedData": {
        "needed": false,
        "variable": "Optional constant or initializer name",
        "notes": "How seed data should be structured if required"
      }
    },
    "criticalPaths": [
      {
        "name": "Primary user flow",
        "steps": [
          "Route enters here",
          "User performs core action",
          "State updates here",
          "Guard or premium check happens here if required by plan"
        ]
      }
    ],
    "implementationRisks": [
      "Potential weak points the coder must avoid"
    ]
  }
}`;

// ─── FILE Marker Parser ─────────────────────────────────────────────────────

/**
 * Strip markdown code fences from a string.
 * Handles: ```tsx\n...\n``` , ```typescript\n...\n``` , ```\n...\n```
 * Works on both outer wrapper and inner per-file fences.
 */
function stripFences(text: string): string {
  let s = text.trim();
  // Strip opening fence: ```lang\n or ```\n
  s = s.replace(/^```\w*\n?/, '');
  // Strip closing fence: \n``` at end
  s = s.replace(/\n?```\s*$/, '');
  return s.trim();
}

function parseFileMarkers(raw: string): Record<string, string> {
  // Strip outer markdown fences
  let cleaned = raw.trim();
  cleaned = cleaned.replace(/^```\w*\s*\n?/, '').replace(/\n?\s*```$/, '');

  const files: Record<string, string> = {};

  // Find all <!--FILE:path--> marker positions
  const markerRe = /<!--FILE:(\/?.+?)-->/g;
  const markers: Array<{ path: string; index: number }> = [];
  let m: RegExpExecArray | null;
  while ((m = markerRe.exec(cleaned)) !== null) {
    markers.push({ path: m[1].trim(), index: m.index + m[0].length });
  }

  if (markers.length === 0) {
    // Fallback: try markdown fenced blocks with filenames
    const fenceRe = /```(?:tsx?|jsx?)\s+(?:\/\/\s*)?([\w/.+-]+\.(?:tsx?|jsx?))\s*\n([\s\S]*?)```/g;
    let fm: RegExpExecArray | null;
    while ((fm = fenceRe.exec(cleaned)) !== null) {
      let path = fm[1].trim();
      if (!path.startsWith('/')) path = '/' + path;
      const content = fm[2].trim();
      if (content.length > 0) files[path] = content;
    }
    // Last resort: entire response as App.tsx
    if (Object.keys(files).length === 0 && cleaned.length > 50) {
      const stripped = stripFences(cleaned);
      files['/App.tsx'] = /(?:import |export |function |const )/.test(stripped)
        ? stripped : cleaned;
    }
    return files;
  }

  // Extract content between consecutive markers (handles missing <!--/FILE-->)
  for (let i = 0; i < markers.length; i++) {
    const start = markers[i].index;
    const end = i + 1 < markers.length
      ? cleaned.lastIndexOf('<!--FILE:', markers[i + 1].index - 1)
      : cleaned.length;

    let content = cleaned.slice(start, end).trim();

    // Remove ALL FILE markers and trailing prose from content
    content = content.replace(/<!--\/?FILE[^>]*-->/g, '').trim();

    // Strip markdown fences inside content
    content = content.replace(/^```\w*\s*\n?/, '').replace(/\n?\s*```$/, '');
    content = content.trim();

    // Remove trailing non-code prose (LLM sometimes adds descriptions after code)
    const lastCodeChar = Math.max(
      content.lastIndexOf('}'),
      content.lastIndexOf(';'),
      content.lastIndexOf('>')
    );
    if (lastCodeChar > 0 && lastCodeChar < content.length - 1) {
      const trailing = content.slice(lastCodeChar + 1).trim();
      if (trailing && /^[A-Z\-\*]/.test(trailing)) {
        content = content.slice(0, lastCodeChar + 1);
      }
    }

    if (content.length > 0) {
      let path = markers[i].path;
      if (!path.startsWith('/')) path = '/' + path;
      files[path] = content;
    }
  }

  return files;
}

// ─── SSE Stream Reader ──────────────────────────────────────────────────────

async function readStream(
  resp: Response,
  onChunk: (text: string) => void,
): Promise<string> {
  const reader = resp.body!.getReader();
  const decoder = new TextDecoder();
  let full = '';
  let buffer = '';  // carry incomplete lines between chunks

  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    buffer += decoder.decode(value, { stream: true });

    const lines = buffer.split('\n');
    // Last element might be incomplete — keep it in buffer
    buffer = lines.pop() || '';

    for (const line of lines) {
      if (!line.startsWith('data: ')) continue;
      const data = line.slice(6);
      if (data === '[DONE]') continue;
      try {
        const parsed = JSON.parse(data);
        const delta = parsed.choices?.[0]?.delta?.content ?? '';
        if (delta) {
          full += delta;
          onChunk(delta);
        }
      } catch { /* skip malformed JSON */ }
    }
  }

  // Process any remaining buffer
  if (buffer.startsWith('data: ')) {
    const data = buffer.slice(6);
    if (data !== '[DONE]') {
      try {
        const parsed = JSON.parse(data);
        const delta = parsed.choices?.[0]?.delta?.content ?? '';
        if (delta) {
          full += delta;
          onChunk(delta);
        }
      } catch { /* skip */ }
    }
  }

  return full;
}

// ─── Preview App Direct Write ──────────────────────────────────────────────

async function writePreviewFile(filePath: string, content: string): Promise<void> {
  const cleanPath = filePath.startsWith('/') ? filePath.slice(1) : filePath;
  // Strip src/ prefix if present — the endpoint writes into preview-app/src/
  const withoutSrc = cleanPath.startsWith('src/') ? cleanPath.slice(4) : cleanPath;
  console.log(`[SimpleGeneration] writePreviewFile: "${filePath}" → preview-app/src/${withoutSrc}`);
  const resp = await fetch('/__write_preview', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ path: withoutSrc, content }),
  });
  if (!resp.ok) {
    throw new Error(`Write failed: ${resp.status}`);
  }
}

async function clearPreview(): Promise<void> {
  await fetch('/__clear_preview', { method: 'POST' });
}

// ─── Helpers ────────────────────────────────────────────────────────────────

/**
 * Strips internal markers from raw LLM output to produce a clean user-facing message.
 * Removes: <think>…</think>, <!--FILE:…--> blocks, fenced code blocks.
 * Falls back to a safe default when nothing meaningful remains.
 */
function cleanCoderMessage(raw: string, fallback = 'Generated files and updated preview.'): string {
  let text = raw;
  // 1. Strip <think>…</think> blocks (greedy, may span multiple lines)
  text = text.replace(/<think>[\s\S]*?<\/think>/gi, '');
  // 2. Strip <!--FILE:…--> markers and their content until the next marker or end
  text = text.replace(/<!--FILE:[\s\S]*?(?=<!--FILE:|<!--\/FILE-->|$)/g, '');
  text = text.replace(/<!--\/FILE-->/g, '');
  // 3. Strip fenced code blocks (```…```)
  text = text.replace(/```[\s\S]*?```/g, '');
  // 4. Strip leftover markdown headings that are just section labels
  text = text.replace(/^##\s+[^\n]*$/gm, '');
  // 5. Collapse whitespace
  text = text.replace(/\n{3,}/g, '\n\n').trim();
  return text.length > 5 ? text.slice(0, 300) : fallback;
}

function djb2(s: string): string {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(16);
}

function makeBlueprint(path: string, content: string): FileBlueprint {
  return {
    id: djb2(path),
    path,
    content,
    role: 'component',
    language: path.endsWith('.css') ? 'css' : 'tsx',
    exports: [],
    dependencies: [],
    hash: djb2(content),
    generatedAt: new Date().toISOString(),
    generatedBy: 'ai',
    isProtected: false,
    userZones: [],
  };
}

function emptyManifest(intent: string): ProductManifest {
  const now = new Date().toISOString();
  return {
    version: 1 as const,
    id: crypto.randomUUID(),
    name: intent.slice(0, 60),
    description: intent,
    intent,
    targetPlatforms: ['web'],
    techStack: {
      framework: 'react',
      language: 'typescript',
      styling: 'tailwind',
      bundler: 'vite',
      backend: null,
      stateManagement: null,
    },
    createdAt: now,
    updatedAt: now,
  } as ProductManifest;
}

function emptyChangePackage(graph: ProjectGraph, ops: FileOperation[]): ChangePackage {
  return {
    plan: [],
    graph,
    fileOperations: ops,
    routeManifest: { routes: [], isMultiPage: false },
    dependencies: [],
    previewMeta: { entryFile: 'src/App.tsx', capabilities: [] },
    guardResults: {
      integration: {
        isHealthy: true, totalIssues: 0, fixedCount: 0,
        reportedCount: 0, unresolvedIssues: [], durationMs: 0,
      },
      integrity: {
        passed: true, errorCount: 0, warnCount: 0,
        errors: [], warnings: [], durationMs: 0,
      },
      runtime: {
        passed: true, failingFiles: [], reasons: [], durationMs: 0,
      },
    },
    warnings: [],
    repairHints: [],
  };
}

/**
 * Normalise LLM file paths to the `src/`-prefixed keys that
 * the code editor expects.
 */
function toSrcKey(path: string): string {
  let p = path.startsWith('/') ? path.slice(1) : path;
  if (!p.startsWith('src/')) p = 'src/' + p;
  return p;
}

// ─── LLM Call Helper ────────────────────────────────────────────────────────

type ModelSlot = 'primary' | 'build' | 'fix';

async function callLLM(
  systemPrompt: string,
  userMessage: string,
  slot: ModelSlot,
  fallbackApiKey: string,
  onStream?: (text: string) => void,
  signal?: AbortSignal,
  maxTokensOverride?: number,
): Promise<string> {
  const modelId = ConfigService.resolveModel(slot as AgentSlot);
  const apiKey = ConfigService.getKeyForAgent(slot as AgentSlot) || fallbackApiKey;

  // Resolve endpoint from the agent's configured provider
  const agentKey = slot === 'primary' ? 'agent_primary' : slot === 'build' ? 'agent_build' : 'agent_fix';
  const provider = ConfigService.getAgentConfig(agentKey).provider || 'openrouter';
  const endpoint = Orchestrator.getEndpoint(provider);

  const messages = [
    { role: 'system', content: systemPrompt },
    { role: 'user', content: userMessage },
  ];

  const body = JSON.stringify({
    model: modelId,
    messages,
    stream: true,
    temperature: 0.3,
    max_tokens: maxTokensOverride ?? (slot === 'build' ? 32000 : 4000),
  });

  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type': 'application/json',
    'HTTP-Referer': window.location.origin,
  };

  // Retry up to 2 times on network errors (ERR_QUIC_PROTOCOL_ERROR, etc.)
  // AbortError (user stop) is not retried.
  const MAX_RETRIES = 2;
  let lastError: unknown;
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      if (signal?.aborted) throw new DOMException('Aborted', 'AbortError');
      const resp = await llmFetchStream(endpoint, headers, body, signal);
      const noop = () => {};
      return await readStream(resp, onStream ?? noop);
    } catch (err: unknown) {
      if (err instanceof DOMException && err.name === 'AbortError') throw err;
      lastError = err;
      if (attempt < MAX_RETRIES) {
        console.warn(`[SimpleGeneration] Network error on attempt ${attempt}, retrying...`, err);
        // Brief pause before retry — let QUIC connection reset
        await new Promise(r => setTimeout(r, 1500 * attempt));
      }
    }
  }
  throw lastError;
}

// ─── Vision Analysis Helper ──────────────────────────────────────────────────

/**
 * Sends an image to the spec-slot model and returns a structured JSON
 * description of the design (color scheme, navigation, components, etc.).
 * Returns '' on any error so callers can degrade gracefully.
 */
async function analyzeImageWithVision(
  imageDataUri: string,
  mimeType: string,
  fallbackApiKey: string,
  onLog?: (msg: string) => void,
  signal?: AbortSignal,
): Promise<string> {
  onLog?.('[Intake] Analyzing image with Vision...');

  const modelId  = ConfigService.resolveModel('spec');
  const apiKey   = ConfigService.getKeyForAgent('spec') || fallbackApiKey;
  const provider = ConfigService.getAgentConfig('agent_spec').provider || 'openrouter';
  const endpoint = Orchestrator.getEndpoint(provider);

  const body = JSON.stringify({
    model: modelId,
    messages: [{
      role: 'user',
      content: [
        { type: 'image_url', image_url: { url: imageDataUri } },
        {
          type: 'text',
          text: `Analyze this screenshot/design reference and extract:
1. App type (what kind of application is this?)
2. Color scheme (primary colors, background color, accent color — give hex codes)
3. Navigation pattern (top bar, bottom tabs, sidebar, none)
4. Key UI components visible (cards, lists, charts, forms, etc.)
5. Layout density (compact/comfortable/spacious)
6. Overall visual style (minimal, colorful, dark, light, etc.)

Respond in JSON format:
{
  "appType": "...",
  "colorScheme": { "background": "#...", "primary": "#...", "accent": "#..." },
  "navigation": "top-nav|bottom-tabs|sidebar|none",
  "components": ["card", "list", ...],
  "density": "compact|comfortable|spacious",
  "style": "...",
  "summary": "One sentence describing this design"
}`,
        },
      ],
    }],
    stream: false,
    temperature: 0.2,
    max_tokens: 1000,
  });

  const headers = {
    'Authorization': `Bearer ${apiKey}`,
    'Content-Type':  'application/json',
    'HTTP-Referer':  window.location.origin,
  };

  try {
    if (signal?.aborted) throw new DOMException('Aborted', 'AbortError');
    const resp = await llmFetch(endpoint, headers, body);
    const data = await resp.json() as { choices?: Array<{ message?: { content?: string } }> };
    const text = (data.choices?.[0]?.message?.content ?? '').trim();
    onLog?.(`[Intake] Vision analysis complete: ${text.slice(0, 120)}`);
    return text;
  } catch (e) {
    if (e instanceof DOMException && e.name === 'AbortError') throw e;
    onLog?.(`[Intake] Vision API error: ${e}`);
    return '';
  }
}

// ─── File Validator ─────────────────────────────────────────────────────────

/**
 * Returns false if the file content is too short, missing code keywords,
 * or has severely mismatched braces (strong sign the LLM truncated output).
 */
function validateFile(path: string, content: string): boolean {
  if (!content || content.trim().length < 20) return false;
  if ((path.endsWith('.tsx') || path.endsWith('.ts')) &&
      !/(?:export|import|function|const)\s/.test(content)) return false;
  const opens  = (content.match(/\{/g) || []).length;
  const closes = (content.match(/\}/g) || []).length;
  if (opens > 0 && Math.abs(opens - closes) > 5) return false;
  return true;
}

// ─── Error File Extractor ────────────────────────────────────────────────────

/**
 * Extracts the relative file path from a Vite error message.
 * Handles patterns like "src/pages/X.tsx", "/src/X.tsx", URL paths.
 */
function extractFileFromError(msg: string): string | null {
  const match = msg.match(/(?:src\/)([\w/.]+\.tsx?)/);
  return match ? match[1] : null;
}

// ─── shadcn Enforcer ────────────────────────────────────────────────────────

/**
 * Validates and auto-fixes LLM output to enforce shadcn/ui components and
 * design tokens. Mutates llmFiles in place.
 */
function enforceShadcn(llmFiles: Record<string, string>, onLog: (msg: string) => void): void {
  const allCode = Object.values(llmFiles).join('\n');
  const hasShadcn    = allCode.includes('@/components/ui/');
  const hasRawButtons = /<button[\s>]/.test(allCode);
  const hasRawInputs  = /<input[\s/]/.test(allCode);
  const hasRawColors  = /bg-(?:blue|green|red|indigo|purple|pink|yellow|orange)-[0-9]/.test(allCode);

  if (!hasShadcn || hasRawButtons || hasRawInputs || hasRawColors) {
    onLog(`[SimpleGeneration] ⚠ shadcn check: imports=${hasShadcn} rawButtons=${hasRawButtons} rawInputs=${hasRawInputs} rawColors=${hasRawColors}`);

    for (const [filePath, content] of Object.entries(llmFiles)) {
      let fixed = content;

      if (/<button[\s>]/.test(fixed)) {
        if (!fixed.includes('@/components/ui/button')) {
          fixed = `import { Button } from "@/components/ui/button";\n` + fixed;
        }
        // Simple tag-name swap — handles multi-line JSX attrs correctly
        fixed = fixed.replace(/<button(\s)/g, '<Button$1');
        fixed = fixed.replace(/<button>/g, '<Button>');
        fixed = fixed.replace(/<\/button>/g, '</Button>');
      }

      if (/<input[\s/]/.test(fixed)) {
        if (!fixed.includes('@/components/ui/input')) {
          fixed = `import { Input } from "@/components/ui/input";\n` + fixed;
        }
        fixed = fixed.replace(/<input(\s)/g, '<Input$1');
        fixed = fixed.replace(/<input\/>/g, '<Input />');
      }

      fixed = fixed.replace(/bg-gray-900/g,        'bg-background');
      fixed = fixed.replace(/bg-gray-800/g,         'bg-card');
      fixed = fixed.replace(/bg-gray-700/g,         'bg-muted');
      fixed = fixed.replace(/text-gray-100/g,       'text-foreground');
      fixed = fixed.replace(/text-gray-300/g,       'text-foreground');
      fixed = fixed.replace(/text-gray-400/g,       'text-muted-foreground');
      fixed = fixed.replace(/text-gray-500/g,       'text-muted-foreground');
      fixed = fixed.replace(/text-white/g,          'text-foreground');
      fixed = fixed.replace(/border-gray-[0-9]+/g,  'border-border');

      if (fixed !== content) {
        llmFiles[filePath] = fixed;
        onLog(`[SimpleGeneration] Auto-fixed: ${filePath}`);
      }
    }
  }
}

// ─── Blueprint formatter ────────────────────────────────────────────────────

function formatBlueprint(plan: any): string {
  const lines: string[] = [];
  const b = plan.blueprint;

  lines.push(`## ${plan.appName}`);
  lines.push(`_${plan.description}_`);
  lines.push('');

  if (plan.targetUser) {
    lines.push(`**Target user:** ${plan.targetUser}`);
    lines.push('');
  }

  if (plan.productStrategy) {
    lines.push('### Product Strategy');
    lines.push(`- **Core action:** ${plan.productStrategy.coreAction}`);
    lines.push(`- **Retention:** ${plan.productStrategy.retentionLoop}`);
    if (plan.productStrategy.paywall?.needed) {
      lines.push(`- **Monetization:** ${plan.productStrategy.paywall.trigger}`);
    }
    lines.push('');
  }

  if (plan.pages?.length) {
    lines.push('### Screens');
    plan.pages.forEach((p: any, i: number) => {
      const guard = p.guard ? ` _(${p.guard})_` : '';
      lines.push(`${i + 1}. **${p.name}** — ${p.purpose}${guard}`);
    });
    lines.push('');
  }

  if (b?.userJourney) {
    lines.push('### User Journey');
    lines.push(b.userJourney);
    lines.push('');
  }

  if (b?.stateMachine) {
    lines.push('### State Machine');
    lines.push(b.stateMachine);
    lines.push('');
  }

  if (b?.logicBlackBox) {
    lines.push('### Logic (Black Box)');
    lines.push(b.logicBlackBox);
    lines.push('');
  }

  if (b?.uiSpec) {
    lines.push('### UI Components');
    lines.push(b.uiSpec);
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Main Service ───────────────────────────────────────────────────────────

export class SimpleGeneration {
  /**
   * Lightweight pre-generation step: ask the LLM whether the user's request
   * is specific enough to build directly, or whether 1-2 clarifying questions
   * would help. Returns null if the intent is already clear or if the call
   * fails (network error, parse error) — callers should treat null as "skip".
   */
  static async clarify(config: {
    intent:  string;
    apiKey:  string;
    signal?: AbortSignal;
  }): Promise<{ questions: string[] } | null> {
    const CLARIFIER_PROMPT = `You are a product advisor. The user wants to build an app.

Analyze their request. If it's clear and specific enough to build — respond with:
{"clear": true}

If it's vague or would benefit from clarification — respond with:
{"clear": false, "questions": ["question1", "question2"]}

RULES:
- Maximum 2 questions. Keep them short and specific.
- Ask about WHAT the app does, not HOW to build it.
- If the user already described features, pages, or specific functionality — it's clear.
- If it's just a category ("fitness app", "todo app") — ask what features.
- Questions should offer concrete options, not open-ended.
- Respond ONLY with JSON. No markdown, no explanation.

EXAMPLES:
User: "fitness app" → {"clear": false, "questions": ["What should it track — workouts, meals, weight, or all three?", "Should it have a social feature like sharing progress?"]}
User: "task manager with projects, tags, and due dates" → {"clear": true}
User: "restaurant app" → {"clear": false, "questions": ["Is this for customers (menu, ordering, reviews) or for staff (table management, orders)?", "Should it support online ordering and delivery?"]}
User: "pregnancy tracker with weekly updates and symptom log" → {"clear": true}`;

    let raw: string;
    try {
      raw = await callLLM(
        CLARIFIER_PROMPT,
        config.intent,
        'primary',
        config.apiKey,
        undefined,
        config.signal,
      );
    } catch (err) {
      // Re-throw user aborts so the caller's abort handling works correctly.
      if (err instanceof DOMException && err.name === 'AbortError') throw err;
      return null; // network / timeout error → skip clarification silently
    }
    try {
      const cleaned = raw.trim().replace(/^```json?\s*\n?/, '').replace(/\n?```\s*$/, '');
      const parsed: unknown = JSON.parse(cleaned);
      if (typeof parsed !== 'object' || parsed === null) return null;
      const p = parsed as Record<string, unknown>;
      if (p['clear'] === true) return null;
      const qs = Array.isArray(p['questions'])
        ? (p['questions'] as unknown[]).filter((q): q is string => typeof q === 'string')
        : [];
      return qs.length > 0 ? { questions: qs } : null;
    } catch {
      return null; // JSON parse failure → skip clarification
    }
  }

  /**
   * Calls a vision-capable model to describe uploaded images.
   * Returns a combined description, or '' on failure.
   */
  static async describeImages(
    images: Array<{ data: string; mimeType: string; name: string }>,
    apiKey: string,
    modelId: string,
    signal?: AbortSignal,
  ): Promise<string> {
    if (images.length === 0) return '';

    const agentConfig = ConfigService.getAgentConfig('agent_primary');
    const provider    = agentConfig.provider || 'openrouter';
    const endpoint    = Orchestrator.getEndpoint(provider);
    const effectiveKey = ConfigService.getKeyForAgent('primary') || apiKey;

    const imageContent = images.map(img => ({
      type: 'image_url' as const,
      image_url: { url: img.data },
    }));

    const messages = [
      {
        role: 'user' as const,
        content: [
          ...imageContent,
          {
            type: 'text' as const,
            text: 'Describe this UI screenshot in detail: layout, colors, components, navigation, spacing, typography. Be specific about what each section contains and how it looks visually. This description will be used to recreate a similar UI.',
          },
        ],
      },
    ];

    const body = JSON.stringify({
      model:       modelId,
      messages,
      stream:      false,
      temperature: 0.2,
      max_tokens:  1000,
    });

    const headers = {
      'Authorization': `Bearer ${effectiveKey}`,
      'Content-Type':  'application/json',
      'HTTP-Referer':  window.location.origin,
    };

    try {
      if (signal?.aborted) throw new DOMException('Aborted', 'AbortError');
      const resp = await llmFetch(endpoint, headers, body);
      const data = await resp.json() as { choices?: Array<{ message?: { content?: string } }> };
      return (data.choices?.[0]?.message?.content ?? '').trim();
    } catch (e) {
      if (e instanceof DOMException && e.name === 'AbortError') throw e;
      console.warn('[SimpleGeneration] Vision API error:', e);
      return '';
    }
  }

  static async run(config: PipelineRunConfig): Promise<GenerationResult> {
    const startMs = Date.now();
    config.onLog('[SimpleGeneration] starting');

    // ── Health check — bridge must be available ───────────────────────────
    try {
      const health = await fetch('/__health_preview');
      if (!health.ok) throw new Error('Preview bridge returned non-OK status');
    } catch (e) {
      config.onLog(`[SimpleGeneration] ❌ Preview bridge unavailable: ${e}`);
      throw new Error('Preview app is not running. Start it with npm run dev:all');
    }

    // ── Detect mode: NEW (no project) or EDIT (project exists) ───────────
    let existingFiles: Record<string, string> = {};
    try {
      const resp = await fetch('/__read_all_preview');
      if (resp.ok) {
        const data = await resp.json() as { files?: Record<string, string> };
        existingFiles = data.files ?? {};
        // Exclude placeholder App.tsx — not real user content
        if (existingFiles['App.tsx']?.includes('Waiting for generation')) {
          delete existingFiles['App.tsx'];
        }
        // Exclude index.css — it is the theme file, not user code
        delete existingFiles['index.css'];
      }
    } catch (e) {
      config.onLog(`[SimpleGeneration] Could not read existing files: ${e}`);
    }

    // EDIT mode requires BOTH: files on disk AND files in useStudio state.
    // If useStudio has no files (singlePageSafeMode=true), user started a new project
    // → force NEW mode even if old files remain on disk (race with clearPreview).
    const studioHasFiles = !config.singlePageSafeMode;
    const isEditMode = studioHasFiles && Object.keys(existingFiles).length > 0;
    config.onLog(`[SimpleGeneration] Mode: ${isEditMode ? 'EDIT' : 'NEW'} (${Object.keys(existingFiles).length} disk files, studioHasFiles=${studioHasFiles})`);

    // ── Process attachments → build visual / doc context ─────────────────
    let attachmentContext = '';
    if (config.attachments?.length) {
      for (const att of config.attachments) {
        if (att.type === 'image' && att.data) {
          const analysis = await analyzeImageWithVision(
            att.data, att.mimeType, config.apiKey, config.onLog, config.signal,
          );
          if (analysis) {
            attachmentContext += `\n\nDESIGN REFERENCE (${att.name}):\n${analysis}`;
          }
        } else if (att.type === 'pdf' && att.textContent) {
          attachmentContext += `\n\nDOCUMENT CONTEXT (${att.name}):\n${att.textContent.slice(0, 3000)}`;
        } else if ((att.type === 'text' || att.type === 'code') && att.data && !att.data.startsWith('data:')) {
          attachmentContext += `\n\nDOCUMENT CONTEXT (${att.name}):\n${att.data.slice(0, 2000)}`;
        }
      }
      if (attachmentContext) {
        config.onLog(`[SimpleGeneration] Attachment context: ${attachmentContext.length} chars`);
      }
    }

    // ── EDIT MODE ─────────────────────────────────────────────────────────
    if (isEditMode) {
      config.onPhase({ phase: 'code', progress: 30 });
      config.onLog('[SimpleGeneration] EDIT mode — skipping Architect');

      const currentCode = Object.entries(existingFiles)
        .map(([p, content]) => `<!--EXISTING_FILE:${p}-->\n${content}`)
        .join('\n\n');

      const editSystemPrompt = `You are editing an existing React application.
The user wants a SPECIFIC change. Apply ONLY what they asked for.

CURRENT APPLICATION:
${currentCode}

RULES:
1. Output ONLY files that need modification using <!--FILE:path--> format.
2. DO NOT include files that don't need changes.
3. PRESERVE all existing functionality, state, imports, and types.
4. Use the same design tokens and shadcn components as the existing code.
5. DO NOT change navigation structure unless explicitly asked.
6. DO NOT rename or restructure files unless explicitly asked.
7. If adding a new feature: add it to the appropriate existing page,
   or create a new page AND update App.tsx routing.
${SHADCN_CHEATSHEET}`;

      const editRaw = await callLLM(
        editSystemPrompt,
        config.intent + attachmentContext,
        'build',
        config.apiKey,
        config.onStream,
        config.signal,
      );
      config.onLog(`[SimpleGeneration] EDIT Coder response: ${editRaw.length} chars`);

      const editLlmFiles = parseFileMarkers(editRaw);
      config.onLog(`[SimpleGeneration] EDIT parsed: ${Object.keys(editLlmFiles).length} files`);

      enforceShadcn(editLlmFiles, config.onLog);

      // ── Level 1: Validate — drop files that look truncated / empty ──────
      for (const [filePath, content] of Object.entries(editLlmFiles)) {
        if (!validateFile(filePath, content)) {
          config.onLog(`[SimpleGeneration] ⚠ EDIT: Skipped invalid: ${filePath}`);
          delete editLlmFiles[filePath];
        }
      }

      // Build finalFiles with src/ keys for code editor display
      const editFinalFiles: Record<string, string> = {};
      for (const [p, content] of Object.entries(editLlmFiles)) {
        editFinalFiles[toSrcKey(p)] = content;
      }

      // FileOperations for useStudio (upsert only — existing files untouched)
      const editOps: FileOperation[] = Object.entries(editFinalFiles)
        .map(([name, content]) => ({ op: 'upsert' as const, name, content }));
      config.onFiles(editOps);

      // Write ONLY changed files — no clearPreview()
      config.onPhase({ phase: 'verify', progress: 85 });
      for (const [p, content] of Object.entries(editLlmFiles)) {
        await writePreviewFile(p, content);
      }
      config.onLog(`[SimpleGeneration] EDIT: wrote ${Object.keys(editLlmFiles).length} files (preserved ${Object.keys(existingFiles).length})`);

      // Signal preview iframe to reload after Vite HMR recompiles
      setTimeout(() => {
        window.dispatchEvent(new CustomEvent('force-preview-reload'));
      }, 2000);

      config.onPhase({ phase: 'idle', progress: 100 });
      const editDurationMs = Date.now() - startMs;
      config.onLog(`[SimpleGeneration] done: ${editOps.length} files, ${editDurationMs}ms`);

      const editNow = new Date().toISOString();
      const editBlueprints: FileBlueprint[] = Object.entries(editFinalFiles).map(
        ([p, c]) => makeBlueprint(p, c),
      );
      const editGraph: ProjectGraph = {
        version: 1 as const,
        id: crypto.randomUUID(),
        projectId: config.projectId ?? '',
        revisionId: config.revisionId ?? '',
        manifest: emptyManifest(config.intent),
        files: editBlueprints,
        routes: [],
        features: [],
        externalDependencies: [],
        entryFileId: djb2('src/App.tsx'),
        createdAt: editNow,
        updatedAt: editNow,
      };

      const editResult: GenerationResult = {
        id: crypto.randomUUID(),
        status: 'complete',
        graph: editGraph,
        operations: editOps,
        message: cleanCoderMessage(editRaw, 'Updated files and refreshing preview.'),
        phase: 'idle' as AgentPhase,
        usedModel: ConfigService.resolveModel('build') || config.modelId,
        selfCorrected: false,
        iterations: 1,
        durationMs: editDurationMs,
        createdAt: editNow,
        changePackage: emptyChangePackage(editGraph, editOps),
        dependencies: [],
        previewMeta: { entryFile: 'src/App.tsx', framework: 'react', isMultiPage: false },
        warnings: [],
        repairHints: [],
      };
      editResult.qualitySummary = GenerationQualityService.evaluate(editResult);
      config.onLog(`[SimpleGeneration] quality: ${editResult.qualitySummary.severity} — ${editResult.qualitySummary.summary}`);
      return editResult;
    }

    // ── NEW MODE ──────────────────────────────────────────────────────────
    const mode = config.generationMode ?? 'app';
    config.onLog(`[SimpleGeneration] Generation mode: ${mode}`);

    const coderTokens = mode === 'landing' ? 8000 : mode === 'superapp' ? 32000 : 16000;

    let plan: Record<string, unknown>;

    // ── Step 1: Architect (primary slot) — JSON plan — SKIPPED if prebuiltPlan ──
    if (config.prebuiltPlan) {
      plan = config.prebuiltPlan as unknown as Record<string, unknown>;
      config.onLog('[SimpleGeneration] Architect skipped — plan from WeeklyFeed (internet-sourced)');
      config.onPhase({ phase: 'code', progress: 30 });
    } else {
      config.onPhase({ phase: 'think', progress: 10 });
      config.onLog('[SimpleGeneration] Step 1: Architect planning...');

      const architectPrompt = mode === 'landing' ? ARCHITECT_PROMPT_LANDING
                            : mode === 'superapp' ? ARCHITECT_PROMPT_SUPERAPP
                            : ARCHITECT_PROMPT;
      const architectTokens = mode === 'landing' ? 2000 : mode === 'superapp' ? 6000 : 6000;

      const planRaw = await callLLM(
        architectPrompt,
        config.intent + attachmentContext,
        'primary',
        config.apiKey,
        undefined,
        config.signal,
        architectTokens,
      );

      try {
        // Log thinking block if present
        const thinkMatch = planRaw.match(/<thinking>([\s\S]*?)<\/thinking>/);
        if (thinkMatch) {
          config.onLog(`[SimpleGeneration] Architect thinking: ${thinkMatch[1].slice(0, 300)}...`);
        }
        // Strip <thinking>...</thinking> block if present, then strip markdown fences
        let jsonPart = planRaw;
        const thinkEnd = planRaw.lastIndexOf('</thinking>');
        if (thinkEnd >= 0) {
          jsonPart = planRaw.slice(thinkEnd + '</thinking>'.length);
        }
        const cleaned = jsonPart.trim().replace(/^```json?\s*\n?/, '').replace(/\n?```\s*$/, '');
        plan = JSON.parse(cleaned);
      } catch {
        plan = {
          appName: 'App',
          description: config.intent,
          theme: 'dark-slate',
          targetUser: 'General user',
          layout: { type: 'single', navigation: 'none' },
          pages: [{ path: '/', name: 'App', file: 'App.tsx', purpose: config.intent, isMainScreen: true, keyElements: [] }],
          dataModel: { entities: [], sharedState: '' },
          shadcnComponents: ['Button', 'Card', 'Input'],
          icons: ['Home'],
        };
        config.onLog('[SimpleGeneration] Plan parse failed, using fallback plan');
      }
    }
    config.onLog(`[SimpleGeneration] Plan: ${JSON.stringify(plan).slice(0, 200)}`);
    console.log('[SimpleGeneration] Architect plan:', plan);

    // Feed plan steps to the UI
    const planSteps = (plan.pages as Array<{ name: string }> | undefined)
      ?.map((p) => p.name) ?? ['App'];
    config.onPlan(planSteps, (plan.appName as string) ?? '');

    // ── Step 1.5: Tech Lead — plan → technical blueprint ───────────────
    config.onLog('[SimpleGeneration] Step 1.5: Tech Lead translating plan...');

    let technicalBlueprint: Record<string, unknown> | null = null;
    try {
      const techLeadRaw = await callLLM(
        TECH_LEAD_PROMPT,
        'PRODUCT PLAN:\n' + JSON.stringify(plan, null, 2),
        'primary',
        config.apiKey,
        undefined,
        config.signal,
        3500,
      );

      const tbCleaned = techLeadRaw
        .replace(/^```json?\n?/, '')
        .replace(/\n?```$/, '')
        .trim();

      const tbParsed = JSON.parse(tbCleaned);
      technicalBlueprint = tbParsed?.technicalBlueprint ?? null;

      config.onLog('[SimpleGeneration] Technical blueprint ready');
    } catch (error) {
      config.onLog('[SimpleGeneration] Tech Lead parse failed — using plan directly');
      console.warn('[SimpleGeneration] Tech Lead parse failed', error);
    }

    // ── Blueprint confirmation flow ──────────────────────────────────────
    const blueprintText = formatBlueprint(plan);

    config.onPlanReady?.({
      plan,
      blueprintText,
      technicalBlueprint,
      appName: (plan.appName as string) ?? '',
      theme:   (plan.theme as string) ?? 'dark-slate',
      pages:   planSteps,
    });

    if (config.waitForConfirmation) {
      const confirmed = await config.waitForConfirmation(plan);
      if (!confirmed) {
        config.onLog('[SimpleGeneration] User cancelled — generation stopped');
        config.onPhase({ phase: 'idle', progress: 0 });
        const cancelNow = new Date().toISOString();
        const emptyGraph: ProjectGraph = {
          version: 1 as const,
          id: crypto.randomUUID(),
          projectId: config.projectId ?? '',
          revisionId: config.revisionId ?? crypto.randomUUID(),
          manifest: emptyManifest(config.intent),
          files: [],
          routes: [],
          features: [],
          externalDependencies: [],
          entryFileId: '',
          createdAt: cancelNow,
          updatedAt: cancelNow,
        };
        return {
          id:            crypto.randomUUID(),
          status:        'cancelled' as const,
          graph:         emptyGraph,
          operations:    [],
          message:       'Generation cancelled by user',
          phase:         'idle' as AgentPhase,
          usedModel:     config.modelId,
          selfCorrected: false,
          iterations:    0,
          durationMs:    Date.now() - startMs,
          planTheme:     (plan.theme as string) ?? 'dark-slate',
          createdAt:     new Date().toISOString(),
          changePackage: emptyChangePackage(emptyGraph, []),
          dependencies:  [],
          previewMeta:   { entryFile: 'src/App.tsx', framework: 'react', isMultiPage: false },
          warnings:      [],
          repairHints:   [],
        };
      }
    }

    // ── Apply theme from Architect plan ───────────────────────────────────
    const themeName = (plan.theme as string) || 'dark-slate';
    const validThemes = ['dark-slate', 'trust', 'warm', 'neon', 'bloom'];
    const selectedTheme = validThemes.includes(themeName) ? themeName : 'dark-slate';

    // Build themed index.css now but write it AFTER clearPreview + LLM files
    // so it always wins over any index.css the LLM may have generated.
    let themedIndexCss: string | null = null;
    try {
      const themeResp = await fetch(`/__read_preview?path=themes/${selectedTheme}.css`);
      if (themeResp.ok) {
        const themeData = await themeResp.json();
        if (themeData.content) {
          themedIndexCss = [
            '@tailwind base;',
            '@tailwind components;',
            '@tailwind utilities;',
            '',
            '@layer base {',
            themeData.content,
            '}',
            '',
            '@layer base {',
            '  * { @apply border-border; }',
            '  body { @apply bg-background text-foreground; }',
            '}',
            '',
            'body {',
            "  font-family: 'Inter', system-ui, -apple-system, sans-serif;",
            '  -webkit-font-smoothing: antialiased;',
            '}',
          ].join('\n');
          config.onLog(`[SimpleGeneration] Theme ready: ${selectedTheme}`);
        }
      } else {
        config.onLog(`[SimpleGeneration] Theme fetch failed (${themeResp.status}), keeping default`);
      }
    } catch (e) {
      config.onLog(`[SimpleGeneration] Theme fetch error: ${String(e)}`);
    }

    // ── Step 2: Coder (build slot) — generate code ────────────────────────
    config.onPhase({ phase: 'code', progress: 40 });
    config.onLog('[SimpleGeneration] Step 2: Coder generating...');

    const coderSystemPrompt = SYSTEM_PROMPT
      + CSS_RECIPES
      + SHADCN_CHEATSHEET
      + '\n\nPRODUCT PLAN (SOURCE OF TRUTH):\n'
      + JSON.stringify(plan, null, 2)
      + (technicalBlueprint
          ? '\n\nTECHNICAL BLUEPRINT (IMPLEMENTATION GUIDE):\n'
            + JSON.stringify(technicalBlueprint, null, 2)
          : '');

    const raw = await callLLM(
      coderSystemPrompt,
      config.intent,
      'build',
      config.apiKey,
      config.onStream,
      config.signal,
      coderTokens,
    );
    config.onLog(`[SimpleGeneration] Coder response: ${raw.length} chars`);

    // 5. Parse files from LLM output
    // Debug: log raw response boundaries to diagnose parse failures
    console.log('[SimpleGeneration] RAW first 500:', raw.slice(0, 500));
    console.log('[SimpleGeneration] RAW last 200:', raw.slice(-200));

    const llmFiles = parseFileMarkers(raw);

    console.log('[SimpleGeneration] FILE markers found:', Object.keys(llmFiles));
    for (const [p, c] of Object.entries(llmFiles)) {
      console.log(`[SimpleGeneration] FILE ${p}: ${c.length} chars, first 80: ${c.slice(0, 80)}`);
    }
    config.onLog(`[SimpleGeneration] parsed: ${Object.keys(llmFiles).length} files`);

    // ── Guard: App.tsx is mandatory — build minimal fallback if LLM skipped it ──
    const hasAppTsx = '/App.tsx' in llmFiles || '/src/App.tsx' in llmFiles;
    if (!hasAppTsx) {
      config.onLog('[SimpleGeneration] ⚠ App.tsx missing from LLM output — generating fallback from plan');
      const planPages = (plan.pages as Array<{ path: string; name: string; file: string }> | undefined) ?? [];
      const routePages = planPages.filter(p => p.file !== 'App.tsx' && p.name !== 'App');

      const importLines = routePages.map(p => {
        const rel = p.file.replace(/^(src\/)?/, './').replace(/\.tsx$/, '');
        return `import ${p.name} from '${rel}';`;
      });
      const routeLines = routePages.map(p =>
        `        <Route path="${p.path}" element={<${p.name} />} />`
      );

      llmFiles['/App.tsx'] = [
        routePages.length > 0 ? `import { BrowserRouter, Routes, Route } from 'react-router-dom';` : '',
        ...importLines,
        '',
        'export default function App() {',
        '  return (',
        routePages.length > 0
          ? `    <BrowserRouter>\n      <Routes>\n${routeLines.join('\n')}\n      </Routes>\n    </BrowserRouter>`
          : '    <div className="min-h-screen bg-background text-foreground" />',
        '  );',
        '}',
      ].filter(l => l !== '').join('\n') + '\n';

      config.onLog(`[SimpleGeneration] Fallback App.tsx generated (${routePages.length} routes)`);
    }

    // ── Enforce shadcn: validate + auto-fix ─────────────────────
    enforceShadcn(llmFiles, config.onLog);

    // ── Level 1: Validate — drop files that look truncated / empty ────────
    for (const [filePath, content] of Object.entries(llmFiles)) {
      if (!validateFile(filePath, content)) {
        config.onLog(`[SimpleGeneration] ⚠ Skipped invalid: ${filePath}`);
        delete llmFiles[filePath];
      }
    }
    // If App.tsx was dropped by validation, regenerate the minimal fallback
    if (!('/App.tsx' in llmFiles) && !('/src/App.tsx' in llmFiles)) {
      const planPages = (plan.pages as Array<{ path: string; name: string; file: string }> | undefined) ?? [];
      const routePages = planPages.filter(p => p.file !== 'App.tsx' && p.name !== 'App');
      const importLines = routePages.map(p => {
        const rel = p.file.replace(/^(src\/)?/, './').replace(/\.tsx$/, '');
        return `import ${p.name} from '${rel}';`;
      });
      const routeLines = routePages.map(p =>
        `        <Route path="${p.path}" element={<${p.name} />} />`
      );
      llmFiles['/App.tsx'] = [
        routePages.length > 0 ? `import { BrowserRouter, Routes, Route } from 'react-router-dom';` : '',
        ...importLines,
        '',
        'export default function App() {',
        '  return (',
        routePages.length > 0
          ? `    <BrowserRouter>\n      <Routes>\n${routeLines.join('\n')}\n      </Routes>\n    </BrowserRouter>`
          : '    <div className="min-h-screen bg-background text-foreground p-8"><p className="text-foreground">App generated. Start chatting to customise.</p></div>',
        '  );',
        '}',
      ].filter(l => l !== '').join('\n') + '\n';
      config.onLog('[SimpleGeneration] App.tsx fallback regenerated after validation');
    }

    // 6. Build final file map with src/ keys for code editor display
    const finalFiles: Record<string, string> = {};
    for (const [path, content] of Object.entries(llmFiles)) {
      finalFiles[toSrcKey(path)] = content;
    }
    config.onLog(`[SimpleGeneration] final files: ${Object.keys(finalFiles).join(', ')}`);

    // 7. Create FileOperations for useStudio editor display
    const ops: FileOperation[] = Object.entries(finalFiles)
      .map(([name, content]) => ({ op: 'upsert' as const, name, content }));
    config.onFiles(ops);

    // 8. Write files to preview-app/src/ — Vite HMR picks them up
    config.onPhase({ phase: 'verify', progress: 85 });

    // Clear previous generated files (keeps main.tsx, index.css, components/, lib/, themes/)
    await clearPreview();

    // Write each LLM-generated file — skip index.css, theme will be applied last
    let writtenCount = 0;
    for (const [path, content] of Object.entries(llmFiles)) {
      const normalised = path.startsWith('/') ? path.slice(1) : path;
      const withoutSrc = normalised.startsWith('src/') ? normalised.slice(4) : normalised;
      if (withoutSrc === 'index.css') {
        config.onLog(`[SimpleGeneration] Skipped LLM index.css (theme will overwrite)`);
        continue;
      }
      await writePreviewFile(path, content);
      writtenCount++;
    }

    // Apply theme last — guaranteed to win over any LLM-generated index.css
    if (themedIndexCss) {
      await writePreviewFile('/index.css', themedIndexCss);
      config.onLog(`[SimpleGeneration] Theme applied: ${selectedTheme}`);
    } else {
      config.onLog(`[SimpleGeneration] No theme CSS — default index.css preserved`);
    }

    config.onLog(`[SimpleGeneration] wrote ${writtenCount} LLM files + theme to preview-app`);

    // Signal preview iframe to reload after Vite HMR picks up the new files.
    // 2 s gives Vite enough time to detect + recompile before the iframe refreshes.
    setTimeout(() => {
      window.dispatchEvent(new CustomEvent('force-preview-reload'));
    }, 2000);

    config.onPhase({ phase: 'idle', progress: 100 });
    const durationMs = Date.now() - startMs;
    config.onLog(`[SimpleGeneration] done: ${ops.length} files, ${durationMs}ms`);

    // 9. Build ProjectGraph (for code editor compatibility)
    const now = new Date().toISOString();
    const blueprints: FileBlueprint[] = Object.entries(finalFiles).map(
      ([p, c]) => makeBlueprint(p, c),
    );
    const graph: ProjectGraph = {
      version: 1 as const,
      id: crypto.randomUUID(),
      projectId: config.projectId ?? '',
      revisionId: config.revisionId ?? '',
      manifest: emptyManifest(config.intent),
      files: blueprints,
      routes: [],
      features: [],
      externalDependencies: [],
      entryFileId: djb2('src/App.tsx'),
      createdAt: now,
      updatedAt: now,
    };

    const changePackage = emptyChangePackage(graph, ops);

    // 10. Return result — preview is handled by Vite HMR on port 3100
    const result: GenerationResult = {
      id: crypto.randomUUID(),
      status: 'complete',
      graph,
      operations: ops,
      message: cleanCoderMessage(raw),
      phase: 'idle' as AgentPhase,
      usedModel: ConfigService.resolveModel('build') || config.modelId,
      selfCorrected: false,
      iterations: 1,
      durationMs,
      planTheme: selectedTheme,
      createdAt: now,
      changePackage,
      dependencies: [],
      previewMeta: { entryFile: 'src/App.tsx', framework: 'react', isMultiPage: false },
      warnings: [],
      repairHints: [],
    };
    result.qualitySummary = GenerationQualityService.evaluate(result);
    config.onLog(`[SimpleGeneration] quality: ${result.qualitySummary.severity} — ${result.qualitySummary.summary}`);
    return result;
  }

  // ── Level 2: Auto-fixer — called on iframe-error ─────────────────────────
  /**
   * Reads the broken file from preview-app, asks the 'fix' agent to repair it,
   * and writes the corrected version back. Returns true if a fix was written.
   */
  static async autoFix(config: {
    errorMsg: string;
    apiKey:   string;
    onLog?:   (msg: string) => void;
    signal?:  AbortSignal;
  }): Promise<boolean> {
    const log = config.onLog ?? (() => {});

    // ── Missing import fast-path ──────────────────────────────────────────────
    // Pattern: Failed to resolve import "./pages/Profile" from "src/App.tsx"
    const missingImportMatch = config.errorMsg.match(
      /Failed to resolve import ["']([^"']+)["'] from ["']([^"']+)["']/,
    );
    if (missingImportMatch) {
      const [, missingModule, sourceFile] = missingImportMatch;
      // Build the file path: strip leading ./ and add .tsx extension
      const missingPath = missingModule.replace(/^\.\//, '') + '.tsx';
      log(`[AutoFix] Missing file detected: ${missingPath} (imported from ${sourceFile})`);

      try {
        // Read the source file for context
        const cleanSource = sourceFile.replace(/^src\//, '');
        const sourceResp = await fetch(`/__read_preview?path=${encodeURIComponent(cleanSource)}`);
        const sourceData = await sourceResp.json() as { content?: string; ok?: boolean };
        const sourceCode = sourceData.content ?? '';

        const fixPrompt = `A React/TypeScript file is missing: ${missingPath}

It is imported in ${sourceFile}:
${sourceCode.slice(0, 2000)}

Generate the missing file ${missingPath}.
Look at how it is used in the imports and JSX/routes to understand what it should contain.
Create a complete, working React component that fits the app style and design tokens.
Use the same shadcn components and design patterns visible in the source file.

Output ONLY the file using <!--FILE:${missingPath}--> marker. No explanation.`;

        log(`[AutoFix] Generating missing file: ${missingPath}...`);
        const fixed = await callLLM(fixPrompt, '', 'fix', config.apiKey, undefined, config.signal);
        const fixedFiles = parseFileMarkers(fixed);

        if (Object.keys(fixedFiles).length === 0) {
          log(`[AutoFix] No content generated for ${missingPath}`);
          return false;
        }

        for (const [path, content] of Object.entries(fixedFiles)) {
          if (!validateFile(path, content)) continue;
          await writePreviewFile(path, content);
          log(`[AutoFix] ✓ Generated missing file: ${path}`);
        }
        return true;
      } catch (e: unknown) {
        if (e instanceof DOMException && e.name === 'AbortError') throw e;
        log(`[AutoFix] Missing-import fix error: ${String(e)}`);
        return false;
      }
    }

    const file = extractFileFromError(config.errorMsg);
    if (!file) {
      log('[AutoFix] Could not extract file from error: ' + config.errorMsg.slice(0, 120));
      return false;
    }

    try {
      const resp = await fetch(`/__read_preview?path=${encodeURIComponent(file)}`);
      if (!resp.ok) {
        log(`[AutoFix] Could not read ${file}: ${resp.status}`);
        return false;
      }
      const data = await resp.json() as { content?: string; ok?: boolean };
      if (!data.ok || !data.content) {
        log(`[AutoFix] No content for ${file}`);
        return false;
      }

      const fixPrompt = `You are fixing a React/TypeScript compilation error.

ERROR:
${config.errorMsg.slice(0, 800)}

FILE: ${file}
${data.content}

Output the COMPLETE fixed file using <!--FILE:${file}--> marker format.
Fix ONLY the error. Keep all existing functionality and imports.
Do not add comments explaining the fix.`;

      log(`[AutoFix] Calling fix agent for ${file}...`);
      const fixed = await callLLM(fixPrompt, '', 'fix', config.apiKey, undefined, config.signal);
      const fixedFiles = parseFileMarkers(fixed);

      if (Object.keys(fixedFiles).length === 0) {
        log('[AutoFix] No files parsed from fix response');
        return false;
      }

      for (const [path, content] of Object.entries(fixedFiles)) {
        if (!validateFile(path, content)) {
          log(`[AutoFix] Skipping invalid fix output for ${path}`);
          continue;
        }
        await writePreviewFile(path, content);
        log(`[AutoFix] ✓ Wrote fix: ${path}`);
      }
      return true;
    } catch (e: unknown) {
      if (e instanceof DOMException && e.name === 'AbortError') throw e;
      log(`[AutoFix] Error: ${String(e)}`);
      return false;
    }
  }
}

// Re-export types so useStudio import stays compatible
export type { GenerationResult, ProjectGraph };
